### ISSUE TITLE
Values on the wheel in the other direction

### ISSUE THREAD

**Issue by JorisDebonnet** [acidb/mobiscroll#109]
My phone runs on Android 4.0. When I use its native scroller, the higher values are higher up on the screen, and the lower values are lower. 

It always takes some getting used to when I switch to the Mobiscrolls, because they do it the other way around: higher values are on the bottom, lower values on the top (at least for date/time). It feels unnatural to me. 

Now I'm just wondering: can anyone verify whether iPhone shows the values in the same order as Mobiscroll or as Android? Just in case iPhone does it the same way as Android, I would strongly vouch to just reverse the order in Mobiscroll as well, as that would be more consistent. In the other case, I'm hoping for an option in the code to reverse the order so that I can set it myself for Android users.

**Comment by dioslaska** [comment]
It's been a while since this issue was opened, but as I see, on every major platform, where scroller like native datepicker exists, the values increase from top to the bottom.

Closing this.
