### ISSUE TITLE
Issue registering click events when we don't use shorthand

### ISSUE THREAD

**Issue by thakurameya** [acidb/mobiscroll#115]
Hello!

I am using mobiscroll.datetime-2.4.1.min.js, I see an issue when we register the click Event on the text field and if we do not use the shorthand ....

<input id="scroller" name="scroller"  onClick='testMe()' />
<input id="scrollerdate" name="scrollerdate"  onClick='testMe()'  type="text"/>
<input id="newscroller" name="newscroller"  onClick='testMe()' />

 $("#scrollerdate").mobiscroll().date(); 
 //$("#scrollerdate").mobiscroll({ preset: 'datetime' }); // This line fails on the 1st Click 2nd Click works fine 

```
function testMe (){
     $("#scroller").mobiscroll().time(); // Shorthand for: $("#scroller").mobiscroll({ preset: 'time' });
     $("#scrollerdate").mobiscroll().date(); 
     //$("#scrollerdate").mobiscroll({ preset: 'datetime' });
```

/\*       $("#scroller").mobiscroll().datetime();
            $('#newscroller').mobiscroll({
            theme     : 'ios',
            preset    :'date',
                dateFormat: 'mm/dd/yy',
                animate   : 'pop',
                display   :'middle',
                showLabel : true,
                minDate: null,
                maxDate: null
        });*/

```
}
```

**Comment by ankitjyashco** [comment]
Hi,
I have purchase the mobiscroll jquery  framework. But when I add my script it gives me error "$(...).mobiscroll(...).time is not a function" How can solve this?
