### ISSUE TITLE
Include Month, Year, and Decade Selector Mode

### ISSUE THREAD

**Issue by pflugs30** [acidb/mobiscroll#116]
I'm very impressed at the Calendar controls features already.  Well done!

One convenience feature I'd love to see is a mode that allows the user to quickly navigate to a different month, year, or decade.  As a reference, I would point to the bootstrap date picker control (http://www.eyecon.ro/bootstrap-datepicker/).  In that control, given the calendar is displayed when the user clicks on the Month header at the top of the calendar, then the calendar changes to a month selector mode, displaying all 12 month names.  When the user clicks on one of the months, the calendar returns to a date display for that month.  This feature allows the user to quickly "jump" from one to the next without paging to each month in between.

Similarly, given the calendar is displayed in month selector mode, when the user clicks again on the header, then the calendar switches to a year selector mode.  Finally, given the calendar is displayed in month year mode, when the user clicks again on the header, then the calendar switches to a decade selector mode.

I believe this feature would combine the function of the date selector control and the calendar selector control into a more compact window that would fit more easily on mobile browsers.  We'd like to use the date and calendar selectors so users can jump between years easily, but we are having a hard time fitting the calendar and date selector on some displays.  I think this feature would make for a more functional and compact control display.

Again, great job on the calendar, and I can't wait to see the next update!
Matthew

**Comment by dioslaska** [comment]
This is done starting from v5
