### ISSUE TITLE
Windows Phone Theme - Month/Day text missing

### ISSUE THREAD

**Issue by ghost** [acidb/mobiscroll#153]
Using the Date & Time Scroller in datetime mode, with Windows Phone Skin month and day names are not being displayed. 
They only show up for the default language (en). If other languages are loaded, names are missing.

**Comment by 111crb111** [comment]
Hi, same problem on all other themes, working only on default language

**Comment by dioslaska** [comment]
Which version are you using?

**Comment by 111crb111** [comment]
/*!
 * Mobiscroll v2.15.0
 * http://mobiscroll.com
 *
 * Copyright 2010-2014, Acid Media
 * Licensed under the MIT license.
 *
 */
