### ISSUE TITLE
"Tap" mode -- similar to "Live" mode

### ISSUE THREAD

**Issue by johnnyshields** [acidb/mobiscroll#165]
Previously (issue #91) you had implemented "Live" mode, where the value in the field is automatically 

I do something slightly different, I'll call "Tap" mode. Like "Live" mode, there are no set/cancel buttons. However, rather that automatically updating the value on each scroll, I only update value when an selection is tapped and I close the window at that time (specifically I use onValueTap method). One advantage to this is that while "Live" mode requires you to click outside the window to close, this way you can select by clicking inside the window (in "Tap" mode, clicking outside the window means "Cancel")

I have some examples Mobiscroll team can look at in my app, will have to give you a login.

**Comment by dioslaska** [comment]
This won't be added as built in functionality, it can be implemented using events and settings.
