### ISSUE TITLE
Listview: mix actions and stages

### ISSUE THREAD

**Issue by dioslaska** [acidb/mobiscroll#234]
The Listview supports swipe actions or action menus. Currently there is no way to mix the two.
Eg. On left swipe: action menu. On right swipe: swipe action

The idea is to support both swipe actions and action menus in the same time.

**Comment by stehlo** [comment]
My case is just an exploration into variations.
For example, the left swipe could reveal 4 or 5 action buttons which pertain to "editing and manipulating" of an item and the right swipe could reveal 2 or 3 buttons which pertain to "use" of an item (start/pause, reset) and "add a new item".

**Comment by stehlo** [comment]
The question though is the level of confusion this could introduce. Maybe...?
