### ISSUE TITLE
datetime: proposing new feature for valid/invalid priority

### ISSUE THREAD

**Issue by psztur** [acidb/mobiscroll#245]
For datetime component you got few options I can use. Two of them are invalid and valid, where valid takes priority - override invalid settings. My use case would appreciate doing it opposite - setting valid dates and overriding few of them by invalid option. I propose to make a switch so that I can choose which comes first.

**Comment by dioslaska** [comment]
Thanks for the suggestion!
However we're not going to implement this for now.
