### ISSUE TITLE
Datetime: store full date & time information

### ISSUE THREAD

**Issue by dioslaska** [acidb/mobiscroll#276]
When setting the date and time using `setVal`, the parts which do not have associated wheels, will be lost (e.g. time information with date only picker, or milliseconds and date information with time only picker), and reset to some defaults.
The desired behavior would be to store all the date information.

**Comment by gotomanners** [comment]
Hi guys thanks for tracking this and looking forward to the fix, should have logged an issue here instead of hassling you on twitter! #fridayBrain

**Comment by dioslaska** [comment]
Done, will be released in 2.15.0
