### ISSUE TITLE
stop propagation on 'onSelect' on Scroller

### ISSUE THREAD

**Issue by lucd** [acidb/mobiscroll#283]
When handling the 'onSelect' event the widget should allow to cancel the select event and keep the user in the modal. It would be useful for doing additional validations just before confirming the selection.

In the docs it is specified that this behavior already exists for the 'onCancel' event by simply returning 'false'. Can this behavior be applied also on the 'onSelect' event?

Thanks.

**Comment by dioslaska** [comment]
What you described is not for the `onCancel`, but for the [onClose](http://docs.mobiscroll.com/2-14-4/datetime#!event-onClose) event. The `onClose` event runs every time when the popup is hiding (on both cancel and select click) and in its `btn` parameter is specified which button triggered the close.

Example code:

    onClose: function (val, btn, inst) {
        if (btn === 'set') {
            // Additional validation here
            return false;
        }
    }
