### ISSUE TITLE
Unable to dismiss jQuery Mobile popup with mobiscroll control in it

### ISSUE THREAD

**Issue by iori57** [acidb/mobiscroll#285]
Mobiscroll version v2.14.3

Mobiscroll controls works fine on normal webpage.

However if I use it with jQuery Mobile popup, for example
```
<div data-role="popup" id="myPopupDiv">
    <input type="text" id="myInput">
</div>
```

And do the steps below:
1) Initialize mobiscroll control with `$('#myInput').mobiscroll().anycontrol()`
2) Showing the popup window with `$( "#myPopupDiv" ).popup( "open" )`
3) Clicking on myInput to show the mobiscroll control once

After this, I cannot dismiss the popup window anymore because no matter where I click, it will reshow the mobiscroll control (in an endless loop)

Is this a known issue?

**Comment by dioslaska** [comment]
I was able to reproduce the issue with 2.14.3, but not with 2.14.4. Looks like whatever caused the issue, it has been fixed.
