### ISSUE TITLE
Is there a way to programatically call a mobiscroll control to show

### ISSUE THREAD

**Issue by iori57** [acidb/mobiscroll#286]
Instead of initializing a mobiscroll control and let it handle the click events and set/cancel events, is there a way to manually show a mobiscroll control, and then when I click 'set' I can get the value and manually propagate it to my input?

This is because with the issue found in (#285), I can't use the normal way to initialize mobiscroll if I'm using it with jQuery Mobile popup component.

**Comment by dioslaska** [comment]
To prevent opening mobiscroll on input tap/focus see the [showOnTap](http://docs.mobiscroll.com/mobiscroll-core#!opt-showOnTap) and [showOnFocus](http://docs.mobiscroll.com/mobiscroll-core#!opt-showOnFocus) settings.

To open mobiscroll programatically, use the [show](http://docs.mobiscroll.com/mobiscroll-core#!method-show) method: `$('#myInput').mobiscroll('show');`
