### ISSUE TITLE
Calendar: rendering issues on WP / Nokia Lumia 735

### ISSUE THREAD

**Issue by dioslaska** [acidb/mobiscroll#289]
See the attached screenshots. It's not reproducable on Lumia 520 with the same OS, the only difference being the screen resolution / pixel density.

![image](https://cloud.githubusercontent.com/assets/324318/6326045/48e13bd4-bb56-11e4-8715-ddc32e02c7f6.png)

![image](https://cloud.githubusercontent.com/assets/324318/6326051/5286cdde-bb56-11e4-8ed9-1de7124a7bfe.png)

![image](https://cloud.githubusercontent.com/assets/324318/6326052/59343c02-bb56-11e4-9ce1-3c0878924a2e.png)

**Comment by dsbl411** [comment]
Hi,
I was the one that reported this issue.

On the same device updated to Windows 10, the issue  doesn't appear.

Please consider this issue closed. 🙂

FYI, the device info :
- Nokia Lumia 735
- Windows 10 Mobile version 1607 (10.0.14393.189) (should be up to date)
- Edge 38.14393.189.0 (should be up to date)
