### ISSUE TITLE
TimerPicker: Wrong default time in Firefox for Android

### ISSUE THREAD

**Issue by roman-e** [acidb/mobiscroll#295]
Hi

I've found a bug in mobiscroll on Firefox for Android. Follow these Steps to reproduce it:
1. Set your Timezone to GMT +0:00 London (It has to be London, Casablanca works fine)
2. Open your Kitchensink Demo "Basic Usage Time" in Firefox for Android.
3. Show the timepicker. It will always show 11:00 PM instead of the actual time.

This bug appears only if you set the Timezone to London, all other values I tried worked as usual.

Kind regards
Roman

**Comment by dioslaska** [comment]
I was able to reproduce it on the latest Firefox for Android. Seems like a Firefox bug, `new Date(1915, 0, 1)` simply returns incorrect time. Strangely it only occurs for specific dates, another example: `new Date(1970, 0, 1)`

I found an old bug report on this: https://bugzilla.mozilla.org/show_bug.cgi?id=487897

Temporary workaround: pass a different start year (default is current year - 100)

    $('#mytime').mobiscroll().time({
        startYear: 2015
    });

**Comment by dioslaska** [comment]
Could not reproduce any more in 2.17.3 and above.
