### ISSUE TITLE
Improving the onClose event

### ISSUE THREAD

**Issue by dioslaska** [acidb/mobiscroll#298]
Currently the `onClose` event runs before the new value is set. There are situations where the user would like to work with the selected value, regardless if Set or Cancel was set. This cannot be done, because in case of a new selection the value is not yet assigned at the time of the `onClose` event.

Possible solutions:

1. Rename the current `onClose` event to `onBeforeClose`. Fire a new event named `onClose` after the value is already set. BRAKES BACKWARD COMPATIBILTY

2. Create a new event, e.g. `onAfterClose`, which runs after the value is set. Naming is not consistent (e.g. with `onBeforeShow` and `onShow`).

**Comment by shamank** [comment]
I recently ran into a similar situation. I needed to re-attach a custom scroller (skrollr) after the popup (with the mobiscroll component) was completly closed and destroyed from the DOM (skrollr needs to recalculate page heights and stuff like that) and I had to resort to ugly code to make it works.

This event is really necessary.

**Comment by dioslaska** [comment]
Added, will be released in 2.17.0
