### ISSUE TITLE
Improve displayed week number

### ISSUE THREAD

**Issue by dioslaska** [acidb/mobiscroll#302]
Currently we display the week number for the first date displayed in the calendar row. If Sunday is the first week, the displayed week number (ISO 8601) is the week number of Sunday, while the week number for the next Monday is different.

A better solution would be to always display the week number of Monday present in the row.

**Comment by anna647** [comment]
hey, Thanks for your good plugin.  However, when i use the select, i wondered if there is a way to reserve my selected value before i change it. Thank you and looking forward to your reply.

**Comment by dioslaska** [comment]
Fixed in 2.16.0
