### ISSUE TITLE
Angular Mobiscroll select problem

### ISSUE THREAD

**Issue by eladh** [acidb/mobiscroll#306]
Hi there.

I'm trying to integrate mobiscroll select with filter and i used the example / demo and its not working . 
i want to use the angular integration like :

we using mobiscroll payed version 2.13.0 with angular integration .
client framework : Angular 1.3 + angular bootstrap 3.x 

```javascript
<select  mobiscroll-options="selectConfiguration" mobiscroll-select="selectedGender"><option ng-value="g.key" ng-repeat="g in $this._getList()">{{ g.value }}</option></select>
```

I got to the keyup event and the grep / sort is working fine but the scroller don't refresh its values ? 
what should we do ? I'm lost here :-( 

1. markup.mobiscroll('setArrayVal', filteredValues, true, true, false, 0); OR - >
2. As in the demo example : 
inst.settings.data = filtered.length ? filtered : [{text: 'No results', value: ''}]; 
inst.settings.parseValue(inst.settings.data[0].value); 
inst.refresh();

- when using the second option i got error that refresh method don't exists. debugging the code i saw that the element was i.scroller , but there wasn't any method named refresh().

my second issue is getting focus on the demo_filter input element , its seems that i got the focus for a sec but after it the select scroller is requesting the focus and i cannot get it back.
even playing with the element Jquery and adding events such as click or tap didn't helped.
when i added timeout based input.click() i got the focus for a sec and then the scroller took it back.

what should i do ?

select  configuration :

```javascript
getSelectOptions() { 
var _this = this; 
return { 

onMarkupReady: function (markup ,inst) { 
var debounce; 
var filtered; 
var query = "";

var element = $('<div style="padding:.5em"><input id="demo_filter" type="text" class="md-filter-input" tabindex="0" placeholder="Type to filter..." /></div>') 
.prependTo($('.dwcc', markup)) 
.on('keydown', function (e) { e.stopPropagation(); }) 
.on('keyup', function (e) { 
var that = $('input', this); 
clearTimeout(debounce); 
debounce = setTimeout(function () { 
query = that.val(); 
filtered = $.grep(_this._getList() , function (val) { 
return (val.text + ', ' + val.value).match(new RegExp(query, 'ig')); 
});

var filteredValues = filtered.length ? filtered : [{text: 'No results', value: ''}];

markup.mobiscroll('setArrayVal', filteredValues, true, true, false, 0);

}, 500); 
});

}, 
onInit: function () { 
var v = $('#demo_dummy').val(); 
$('#demo_dummy').val($(v).find('.md-airport-name').text()); 
}, 
onValueTap: function (item, inst) { 
var text = item.find('.md-airport-name').text(); 
$('#demo_filter').val(text); 
}, 
rtl: false, 
display: 'bubble', 
cancelText: 'close', 
setText: 'select' 
} 
}
```

Thanks in advance,
elad hirsch

**Comment by eladh** [comment]
Hi again :-)

when i changed the code to this : i got the focus but not on mobile devices ...

```javascript
    onMarkupReady: function (markup , inst) {
                        var filter = $('<input id="demo_filter" type="text" class="md-filter-input" tabindex="0" placeholder="Type to filter..." />');
                        var div = $('<div style="padding:.5em"></div>');
                        div.append(filter);
                        div.prependTo($('.dwcc', markup));
                        filter.on('click', function (){
                            filter.focus();
                        });
                        filter.on('tap', function (){
                            filter.focus();
                        });
                    },
```

**Comment by eladh** [comment]
After upgrading to mobiscroll 2.15.1 - fixed.

**Comment by dioslaska** [comment]
Discussion moved to support.
