### ISSUE TITLE
Trigger switch between controls

### ISSUE THREAD

**Issue by barmmie** [acidb/mobiscroll#307]
Hi,

i am using the calendar and time controls  controls: ['calendar', 'time'],
I want  to switch to the time control once a user sets the date control
i have the mobiscroll instance from the onDayChange
What method do i call on the mobiScroll instance to switch the control to the time control

Thanks

**Comment by dioslaska** [comment]
Hi,

As this is not a product related bug / feature request, please submit a support ticket on http://mobiscroll.com/support using the account with you purchased a license or activated a trial.

Thanks
