### ISSUE TITLE
Calendar: Add a CSS class to marked day containers.

### ISSUE THREAD

**Issue by mortargrind** [acidb/mobiscroll#308]
Hi,

I'm trying to change background color and text color of the marked day cells in calendar. But currently there's no CSS class is being added to the "dw-cal-day" element; just "dw-cal-day-m" element is now being added to "dw-i" element. Since "dw-cal-day-m" is the middle element of the "dw-i" child elements; I can not write a CSS selector for "dw-cal-day-fg" element that are predecessor of the "dw-cal-day-m" elements. 

Any suggestions?

**Comment by dioslaska** [comment]
Added in 2.16.0
