### ISSUE TITLE
Incorrect week counter 

### ISSUE THREAD

**Issue by dsbl411** [acidb/mobiscroll#311]
Hi, 
On your demo website the week counter is incorrect as you can see in the attached screenshots. 
Best regards, 
![screenshot_2015-06-09-00-02-57](https://cloud.githubusercontent.com/assets/8678307/8046615/b1d7ef64-0e3c-11e5-876a-3035917c6590.png)
![screenshot_2015-06-09-00-02-17](https://cloud.githubusercontent.com/assets/8678307/8046622/ba74d254-0e3c-11e5-9724-3fa0bb5538c7.png)

**Comment by dioslaska** [comment]
Merged into #302.
