### ISSUE TITLE
Incorrect week selection 

### ISSUE THREAD

**Issue by dsbl411** [acidb/mobiscroll#312]
Hi, 
On your demo website the week selection is incorrect as you can see in the attached screenshots. 
For the English locale, the selection should start on Sundays and for the French locale on Mondays. 
![screenshot_2015-06-09-00-08-35](https://cloud.githubusercontent.com/assets/8678307/8046675/2130edc0-0e3d-11e5-8000-e00e9b89f73d.png)
![screenshot_2015-06-09-00-08-18](https://cloud.githubusercontent.com/assets/8678307/8046678/267e6208-0e3d-11e5-94d9-88cf6bf7915e.png)

Best regards,

**Comment by dioslaska** [comment]
The first day of the selected week is defined by the `firstSelectDay` setting, which is set to 6 (Saturday) in the referenced demo. If the `firstSelectDay` setting is not explicitly set, it will use the `firstDay` setting of the locale settings and will work as mentioned above.
