### ISSUE TITLE
Spelling mistake in the French locale 

### ISSUE THREAD

**Issue by dsbl411** [acidb/mobiscroll#313]
Hi, 
There is a spelling mistake in the French translation of the "SET" action. It should be "TERMINER" instead.
Best regards, 

![screenshot_2015-06-09-00-08-18](https://cloud.githubusercontent.com/assets/8678307/8046746/dce4a96c-0e3d-11e5-8426-efad48d24665.png)

**Comment by dioslaska** [comment]
Fixed in 2.16.0
