### ISSUE TITLE
Multiple select improvments

### ISSUE THREAD

**Issue by dsbl411** [acidb/mobiscroll#315]
Hi,

In the calendar with multi day select, for the number of items selected label, the plural form "sélectionnés" must be used in French when more than one items are selected.
I'm no expert but I think you should also use the plural form for the Spanish, Portuguese and Italian locales.
![multiple select calendar](https://cloud.githubusercontent.com/assets/8678307/8253277/86ab6294-168e-11e5-92df-15c5b3cc4586.PNG)

Also, I wish you could add the number of items selected for the multiple select control. We had returns from users who found the multiple select not really easy to understand when no items are selected. I think it is clearer as in the mockup below.
![multiple-selection-select](https://cloud.githubusercontent.com/assets/8678307/8253325/fe64b010-168e-11e5-87c1-c2b8b91278d2.jpg)

Thanks.

Best regards,

P.S. Really nice new form controls BTW :-)

**Comment by dioslaska** [comment]
Thanks for the notice. We'll find a solution for that.

For the multilple select you can also display the number of selected items using the counter settings (http://docs.mobiscroll.com/2-16-0/select#!opt-counter)

**Comment by dioslaska** [comment]
Fixed in 2.16.1
