### ISSUE TITLE
Feature request: Select with Autocomplete via AJAX

### ISSUE THREAD

**Issue by shamank** [acidb/mobiscroll#319]
It would be great if the current Select component could handle AJAX requests as data source.
I know it should be possible to make it works anyway by manipulating the current component events, but it's a real pain. I'm currently using jQM AJAX autocomplete, but it's horripilant and required 2 tons of code.

**Comment by dioslaska** [comment]
Added in 3.2.0. Demo here: https://demo.mobiscroll.com/select#demo=autocomplete
