### ISSUE TITLE
Scroll issues with multiple group select

### ISSUE THREAD

**Issue by dsbl411** [acidb/mobiscroll#320]
Hi,

There are some issues with the scrolling in the multiple group select control.

Sometimes, the 'A-Z wheel'  gets out of sync with the items as you can see in the video below:
http://1drv.ms/1LwBmQY

Also, sometimes, a small drag completely changes the items as you can see in the video below:
http://1drv.ms/1LwBFen

Both those issues happens with Chrome and Safari on iOS 8.

Best regards,

**Comment by dioslaska** [comment]
Fixed in 2.16.1
