### ISSUE TITLE
Tap on Mobiscroll overlay or buttons, triggers the unexpected tap on underlying clickable elements.

### ISSUE THREAD

**Issue by seycRDTEK** [acidb/mobiscroll#326]
Tap on Mobiscroll overlay or buttons, triggers the unexpected tap on underlying clickable elements.
It is mentioned that this issue is fixed in 2.16.0 but I am facing the same issue with 2.16.0 too.
Please suggest how to resolve this issue

**Comment by dioslaska** [comment]
On what platform and browser are you experiencing this issue?

**Comment by seycRDTEK** [comment]
Related platforms are ios and android 4.x and this issue is occurring in apk/ipa files and also in the native browsers.

**Comment by dioslaska** [comment]
I checked it once again on various Android and iOS versions, but I'm not able to reproduce it in our test enviroment: tapping over native form elements (input, select, button), and tapping over div elements with click event attached.

Can you create a test case, or perhaps a live link where I can see the problem?

Thanks

**Comment by dioslaska** [comment]
Any updates on this?
