### ISSUE TITLE
Issue with "mixed" mode

### ISSUE THREAD

**Issue by seycRDTEK** [acidb/mobiscroll#327]
Only for the theme "android"  + and - buttons are displayed when mode is set to "mixed" and for remaining themes up/down arrow icons are displayed. 
Is it a default behavior? If yes, then how can we set +/- for remaining themes? (Version 2.16.0)

**Comment by dioslaska** [comment]
The themes mimic the look and feel of the specific platform. E.g. the datepicker on Android Holo (4.x) have arrows, not +/- buttons.

Of course you can add any styling to the buttons using css.

Another alternative is to specify the icon classes, but you need to make sure the used icons are included in the downloaded package:

    $('#mydate').mobiscroll().date({
        btnPlusClass: 'mbsc-ic mbsc-ic-plus',
        btnMinusClass: 'mbsc-ic mbsc-ic-minus'
    });

The above settings are not documented, they are used internally by the supplied themes, but you can use them safely.
