### ISSUE TITLE
JQM, RejuireJS - Select control:  Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kostap13** [acidb/mobiscroll#330]
I try it with github and trial version on devices and emulators. It works fine only in browser. 

	shim: {
        ......
        "mobiscroll" : ["jquerymobile"],
--------------------------

            $('#someSelector').mobiscroll().select({
                theme: "android-holo-light",     // Specify theme like: theme: 'ios' or omit setting to use default
                mode: "mixed",       // Specify scroller mode like: mode: 'mixed' or omit setting to use default
                display: "modal", // Specify display mode like: display: 'bottom' or omit setting to use default
                inputClass: 'na-form__ti'
            });

Stack trace:

Uncaught RangeError: Maximum call stack size exceeded.m.event.special.focus.trigger @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3(anonymous function) @ jquery-1.11.1.min.js:3m.extend.each @ jquery-1.11.1.min.js:2m.fn.m.each @ jquery-1.11.1.min.js:2m.fn.extend.trigger @ jquery-1.11.1.min.js:3m.each.m.fn.(anonymous function) @ jquery-1.11.1.min.js:4a.fn.extend.focus @ jquery.mobile-1.4.3.js:282J @ mobiscroll.custom-2.16.0.min.js:10m.event.dispatch @ jquery-1.11.1.min.js:3m.event.add.r.handle @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3(anonymous function) @ jquery-1.11.1.min.js:3m.extend.each @ jquery-1.11.1.min.js:2m.fn.m.each @ jquery-1.11.1.min.js:2m.fn.extend.trigger @ jquery-1.11.1.min.js:3m.each.m.fn.(anonymous function) @ jquery-1.11.1.min.js:4a.fn.extend.focus @ jquery.mobile-1.4.3.js:282a.widget._handleDocumentFocusIn @ jquery.mobile-1.4.3.js:10501(anonymous function) @ jquery.mobile-1.4.3.js:927h @ jquery.mobile-1.4.3.js:1230m.event.dispatch @ jquery-1.11.1.min.js:3m.event.add.r.handle @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3m.event.simulate @ jquery-1.11.1.min.js:3k.focusinBubbles.m.each.c @ jquery-1.11.1.min.js:3m.event.special.focus.trigger @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3(anonymous function) @ jquery-1.11.1.min.js:3m.extend.each @ jquery-1.11.1.min.js:2m.fn.m.each @ jquery-1.11.1.min.js:2m.fn.extend.trigger @ jquery-1.11.1.min.js:3m.each.m.fn.(anonymous function) @ jquery-1.11.1.min.js:4a.fn.extend.focus @ jquery.mobile-1.4.3.js:282J @ mobiscroll.custom-2.16.0.min.js:10m.event.dispatch @ jquery-1.11.1.min.js:3m.event.add.r.handle @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3m.event.simulate @ jquery-1.11.1.min.js:3k.focusinBubbles.m.each.c @ jquery-1.11.1.min.js:3m.event.special.focus.trigger @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3(anonymous function) @ jquery-1.11.1.min.js:3m.extend.each @ jquery-1.11.1.min.js:2m.fn.m.each @ jquery-1.11.1.min.js:2m.fn.extend.trigger @ jquery-1.11.1.min.js:3m.each.m.fn.(anonymous function) @ jquery-1.11.1.min.js:4a.fn.extend.focus @ jquery.mobile-1.4.3.js:282a.widget._handleDocumentFocusIn @ jquery.mobile-1.4.3.js:10501(anonymous function) @ jquery.mobile-1.4.3.js:927h @ jquery.mobile-1.4.3.js:1230m.event.dispatch @ jquery-1.11.1.min.js:3m.event.add.r.handle @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3m.event.simulate @ jquery-1.11.1.min.js:3k.focusinBubbles.m.each.c @ jquery-1.11.1.min.js:3m.event.special.focus.trigger @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3(anonymous function) @ jquery-1.11.1.min.js:3m.extend.each @ jquery-1.11.1.min.js:2m.fn.m.each @ jquery-1.11.1.min.js:2m.fn.extend.trigger @ jquery-1.11.1.min.js:3m.each.m.fn.(anonymous function) @ jquery-1.11.1.min.js:4a.fn.extend.focus @ jquery.mobile-1.4.3.js:282J @ mobiscroll.custom-2.16.0.min.js:10m.event.dispatch @ jquery-1.11.1.min.js:3m.event.add.r.handle @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3m.event.simulate @ jquery-1.11.1.min.js:3k.focusinBubbles.m.each.c @ jquery-1.11.1.min.js:3m.event.special.focus.trigger @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3(anonymous function) @ jquery-1.11.1.min.js:3m.extend.each @ jquery-1.11.1.min.js:2m.fn.m.each @ jquery-1.11.1.min.js:2m.fn.extend.trigger @ jquery-1.11.1.min.js:3m.each.m.fn.(anonymous function) @ jquery-1.11.1.min.js:4a.fn.extend.focus @ jquery.mobile-1.4.3.js:282a.widget._handleDocumentFocusIn @ jquery.mobile-1.4.3.js:10501(anonymous function) @ jquery.mobile-1.4.3.js:927h @ jquery.mobile-1.4.3.js:1230m.event.dispatch @ jquery-1.11.1.min.js:3m.event.add.r.handle @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3m.event.simulate @ jquery-1.11.1.min.js:3k.focusinBubbles.m.each.c @ jquery-1.11.1.min.js:3m.event.special.focus.trigger @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3(anonymous function) @ jquery-1.11.1.min.js:3m.extend.each @ jquery-1.11.1.min.js:2m.fn.m.each @ jquery-1.11.1.min.js:2m.fn.extend.trigger @ jquery-1.11.1.min.js:3m.each.m.fn.(anonymous function) @ jquery-1.11.1.min.js:4a.fn.extend.focus @ jquery.mobile-1.4.3.js:282J @ mobiscroll.custom-2.16.0.min.js:10m.event.dispatch @ jquery-1.11.1.min.js:3m.event.add.r.handle @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3m.event.simulate @ jquery-1.11.1.min.js:3k.focusinBubbles.m.each.c @ jquery-1.11.1.min.js:3m.event.special.focus.trigger @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3(anonymous function) @ jquery-1.11.1.min.js:3m.extend.each @ jquery-1.11.1.min.js:2m.fn.m.each @ jquery-1.11.1.min.js:2m.fn.extend.trigger @ jquery-1.11.1.min.js:3m.each.m.fn.(anonymous function) @ jquery-1.11.1.min.js:4a.fn.extend.focus @ jquery.mobile-1.4.3.js:282a.widget._handleDocumentFocusIn @ jquery.mobile-1.4.3.js:10501(anonymous function) @ jquery.mobile-1.4.3.js:927h @ jquery.mobile-1.4.3.js:1230m.event.dispatch @ jquery-1.11.1.min.js:3m.event.add.r.handle @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3m.event.simulate @ jquery-1.11.1.min.js:3k.focusinBubbles.m.each.c @ jquery-1.11.1.min.js:3m.event.special.focus.trigger @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3(anonymous function) @ jquery-1.11.1.min.js:3m.extend.each @ jquery-1.11.1.min.js:2m.fn.m.each @ jquery-1.11.1.min.js:2m.fn.extend.trigger @ jquery-1.11.1.min.js:3m.each.m.fn.(anonymous function) @ jquery-1.11.1.min.js:4a.fn.extend.focus @ jquery.mobile-1.4.3.js:282J @ mobiscroll.custom-2.16.0.min.js:10m.event.dispatch @ jquery-1.11.1.min.js:3m.event.add.r.handle @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3m.event.simulate @ jquery-1.11.1.min.js:3k.focusinBubbles.m.each.c @ jquery-1.11.1.min.js:3m.event.special.focus.trigger @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3(anonymous function) @ jquery-1.11.1.min.js:3m.extend.each @ jquery-1.11.1.min.js:2m.fn.m.each @ jquery-1.11.1.min.js:2m.fn.extend.trigger @ jquery-1.11.1.min.js:3m.each.m.fn.(anonymous function) @ jquery-1.11.1.min.js:4a.fn.extend.focus @ jquery.mobile-1.4.3.js:282a.widget._handleDocumentFocusIn @ jquery.mobile-1.4.3.js:10501(anonymous function) @ jquery.mobile-1.4.3.js:927h @ jquery.mobile-1.4.3.js:1230m.event.dispatch @ jquery-1.11.1.min.js:3m.event.add.r.handle @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3m.event.simulate @ jquery-1.11.1.min.js:3k.focusinBubbles.m.each.c @ jquery-1.11.1.min.js:3m.event.special.focus.trigger @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3(anonymous function) @ jquery-1.11.1.min.js:3m.extend.each @ jquery-1.11.1.min.js:2m.fn.m.each @ jquery-1.11.1.min.js:2m.fn.extend.trigger @ jquery-1.11.1.min.js:3m.each.m.fn.(anonymous function) @ jquery-1.11.1.min.js:4a.fn.extend.focus @ jquery.mobile-1.4.3.js:282J @ mobiscroll.custom-2.16.0.min.js:10m.event.dispatch @ jquery-1.11.1.min.js:3m.event.add.r.handle @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3m.event.simulate @ jquery-1.11.1.min.js:3k.focusinBubbles.m.each.c @ jquery-1.11.1.min.js:3m.event.special.focus.trigger @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3(anonymous function) @ jquery-1.11.1.min.js:3m.extend.each @ jquery-1.11.1.min.js:2m.fn.m.each @ jquery-1.11.1.min.js:2m.fn.extend.trigger @ jquery-1.11.1.min.js:3m.each.m.fn.(anonymous function) @ jquery-1.11.1.min.js:4a.fn.extend.focus @ jquery.mobile-1.4.3.js:282a.widget._handleDocumentFocusIn @ jquery.mobile-1.4.3.js:10501(anonymous function) @ jquery.mobile-1.4.3.js:927h @ jquery.mobile-1.4.3.js:1230m.event.dispatch @ jquery-1.11.1.min.js:3m.event.add.r.handle @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3m.event.simulate @ jquery-1.11.1.min.js:3k.focusinBubbles.m.each.c @ jquery-1.11.1.min.js:3m.event.special.focus.trigger @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3(anonymous function) @ jquery-1.11.1.min.js:3m.extend.each @ jquery-1.11.1.min.js:2m.fn.m.each @ jquery-1.11.1.min.js:2m.fn.extend.trigger @ jquery-1.11.1.min.js:3m.each.m.fn.(anonymous function) @ jquery-1.11.1.min.js:4a.fn.extend.focus @ jquery.mobile-1.4.3.js:282J @ mobiscroll.custom-2.16.0.min.js:10m.event.dispatch @ jquery-1.11.1.min.js:3m.event.add.r.handle @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3m.event.simulate @ jquery-1.11.1.min.js:3k.focusinBubbles.m.each.c @ jquery-1.11.1.min.js:3m.event.special.focus.trigger @ jquery-1.11.1.min.js:3m.event.trigger @ jquery-1.11.1.min.js:3(anonymous function) @ jquery-1.11.1.min.js:3m.extend.each @ jquery-1.11.1.min.js:2m.fn.m.each @ jquery-1.11.1.min.js:2m.fn.extend.trigger @ jquery-1.11.1.min.js:3m.each.m.fn.(anonymous function) @ jquery-1.11.1.min.js:4a.fn.extend.focus @ jquery.mobile-1.4.3.js:282a.widget._handleDocumentFocusIn @ jquery.mobile-1.4.3.js:10501(anonymous function) @ jquery.mobile-1.4.3.js:927

**Comment by dioslaska** [comment]
I created a test case based on the above (with a trial package), but it works fine for me.

You can download it here: https://dl.dropboxusercontent.com/u/34664815/mobiscroll.require.zip

If you can modify it to reproduce the problem, let me know.

**Comment by dioslaska** [comment]
Any updates on this? Is the example working for you?

**Comment by dioslaska** [comment]
Closing: cannot reproduce.
