### ISSUE TITLE
Scrollview branch demo doesn't work?

### ISSUE THREAD

**Issue by MRokas** [acidb/mobiscroll#334]
TypeError: inst.changeWheel is not a function mobiscroll.listbase.js:403:29
TypeError: inst.changeWheel is not a function mobiscroll.select.js:583:29
TypeError: ms.classes.ScrollView is not a constructor mobiscroll.scroller.js:830:35

Tested on Firefox41, IE11, and Chrome42

**Comment by dioslaska** [comment]
It works now
