### ISSUE TITLE
Date wheel scrolling into infinite loop

### ISSUE THREAD

**Issue by seycRDTEK** [acidb/mobiscroll#335]
while selecting the date some time the wheel scrolls into infinite loop.

Using android 4.1 and date api in scroller mode and phonegap.

another issue in the video is when we keep tapping on the arrow, suddenly the mobiscroll closes.

please see the video on the below url.

https://drive.google.com/file/d/0BwNuEKato6uEbXFtdWdnRW1iZXM/view?usp=sharing

**Comment by dioslaska** [comment]
Hi,

1. By infinite loop you mean when the wheel keeps scrolling after you released the button on the video?

2. I think the sudden close occurs when you tap to close to the cancel button, and accidentally it's tapped. I don't see it happening with the up arrows. Maybe increasing the spacing between the arrows and buttons would help.

**Comment by seycRDTEK** [comment]
yes, infinite loop means the wheel keeps scrolling even after i released the button.

**Comment by seycRDTEK** [comment]
do we have any method in the API to increase the space between the scroller and the buttons?

**Comment by dioslaska** [comment]
There is no API setting for that, you can use custom css, like:

    .mbsc-android-holo .dwc {
        padding-bottom: .625em;
    }

**Comment by dioslaska** [comment]
Fixed, will be released in 2.17.0

**Comment by seycRDTEK** [comment]
Hello dioslaska,

Thanks a lot for your answer and nice that the bug will be fixed in 2.17.0.

Could you say me if you have a delivery date for the 2.17.0 ?

We are trying to report the modification in our mobiscroll installed version (we are using right now the 2.16.0). However, we have only one source (mobiscroll.custom-2.16.0.min.js which is an optimized one without commentaries). But you are mentionning mobiscroll.scroll.js with the correction you did on it
(note that we search into mobiscroll.custom-2.16.0.min.js  for instance some variables like onBtnEnd or 
onBtnStart), but impossible to find them (tried on 2.16.1 too but it is the same).

So how we can report this on a 2.16.0 (or 2.16.1 version) ?

Thanks a lot for your answer,
Regards

**Comment by lokeshsamrit** [comment]
Is there any workaround for this issue , and is there any dependency with jquery versions ?
