### ISSUE TITLE
Conflict with Bootstrap modal

### ISSUE THREAD

**Issue by dioslaska** [acidb/mobiscroll#341]
"Maximum call stack size exceeded" error is thrown when mobiscroll is used in modal mode inside a Bootstrap modal window.

The bootstrap modal enforces that the focus cannot leave the modal itself. The mobiscroll popup does the same, and this causes the conflict.

As a workaround mobiscroll focus listener can be removed in the `onShow` event:

    $('#myField').mobiscroll().date({
        onShow: function () {
            $(window).off('focusin');
       }
    });

**Comment by geeyan** [comment]
Thank you, it works!

**Comment by dioslaska** [comment]
Looks like the above workaround works only if mobiscroll is shown with animation.

Another solution is to stop the focus trap on the bootstrap modal:

    $.fn.modal.Constructor.prototype.enforceFocus = function () {};

**Comment by dioslaska** [comment]
As of Mobiscroll 2.17.0 the following can be used:

    $('#myField').mobiscroll().date({
        focusTrap: false  
    });
