### ISSUE TITLE
Date & Time: make it easier work with UTC dates + client independent time

### ISSUE THREAD

**Issue by dioslaska** [acidb/mobiscroll#350]
Also, think about a mode, where server time could be passed to the control, so it will be able to work independent from the client time, which might be incorrect.

**Comment by aschwartz-satcom** [comment]
+1
Editing a time in UTC is a common task for many industries.  Casting dates from UTC to local and back just to present an editor is annoying.

**Comment by dioslaska** [comment]
Since [v4.4.2](https://mobiscroll.com/releases#v420) we support working with `iso8601` strings. The optional timezone part is not taken into account, e.g. `'2018-11-28T10:00'`, `'2018-11-28T10:00Z'`, `'2018-11-28T10:00-2:00'` will all show up as 10:00 AM on the time wheels.
