### ISSUE TITLE
Calendar/Range on IE9 very slow

### ISSUE THREAD

**Issue by Rendez** [acidb/mobiscroll#353]
Measuring performance on IE9 is very tedious, but before I would like to know if there's known performance issues on IE9. The Calendar seems to open after a very very long time, but the browser either chokes on JS execution or even memory. I will do my best to provision a machine with Windows 7 with IE9 to give more info.

Any more information on this?

I'm using the latest Mobiscroll Range component with jQuery.

**Comment by Rendez** [comment]
Ok good news, I've found a very good and simple improvement.

First, the performance issues where happening in a multi month (3 months in my case) view with `display: bubble`. Digging into JS and CSS I found that the displayed month rows contaning `hasLayout` because of its `position: absolute` are very expensive for the rendering engine.
The calendar was taking between 3-4 seconds on IE9 to even be ready for display, as IE9 blocks the interface until it considers the layout is ready... This made everything unusable, switching months, etc.

Applying this line of CSS, somehow helps IE to ease out on the amount of calculations it has to do on the months rows, which contain so many DOM elements...

```css
.dw-cal-anim-c {
    transform: translate(0,0);
}
```

After applying this, IE9 specially renders the calendar in < 1s, almost as fast as Chrome and Firefox!

Curious to see if the same patch would have an effect on Chrome too, I added the corresponding `hack` for it, to trigger composition in the layout:

```css
.dw-cal-anim-c {
    transform: translate(0,0);
    transform: translate3d(0,0,0);
}
```

Here are the results of the profiler:

### Without the fix
<img width="787" alt="wout" src="https://cloud.githubusercontent.com/assets/61776/9963479/c30523a8-5e2b-11e5-8958-990255f22304.png">

### With the fix
<img width="729" alt="with" src="https://cloud.githubusercontent.com/assets/61776/9963478/c2e62d68-5e2b-11e5-983f-24e1200a1cfb.png">

**Comment by dioslaska** [comment]
Thanks for the time and effort you put investigating this issue.

I will of course test it to see if this change has some unwanted side effects.

The `.dw-cal-anim-c` div already had `-webkit-backface-visibility: hidden` style on it, which solved animation performance issues on iOS, changing that to `-webkit-transform: translate3d(0,0,0);` should have the same effect. 

The 2D transform should effect only IE9, as right after it's overridden by the 3D transform on every other supported platform.

There are still performance issues on IE / Edge on Windows (Phone) (#224), mostly on handheld devices with lower performance. It takes some to show the calendar.

Unfortunately there are quiet a lot of expensive width / height calculations for positioning the popup, and another set for making the month swipe to work. With the complexity of the markup this has a high impact on performance. 

We're constantly trying to simplify, improve this, but currently wasn't able to reduce the problem to some specific css rule or offset calculation, it's rather a combination of multiple calculations.

**Comment by Rendez** [comment]
Correct, this two CSS rules should improve performance on most browsers. Once you can confirm no side-effect exist, we should close this issue.

As for the WP8 performance problems, I won't be able to get my hands on a real Windows Phone device and spend time debugging it. I would bet the issue goes along the same lines, as paint time seems more problematic than JS performance in IE10 and above.

Cheers,

**Comment by dioslaska** [comment]
I'm testing this currently on IE9 / Win7 / VirtualBox, using multiple months and bubble display.
I see no time difference if I apply the transform styling, in my test site it always appeared within 1 second. The `scrollTo` call you mentioned runs in 40ms. My guess is that it depends on page content also which is scrolled.

Another note: using `transform: translate(0,0);` is not recognized in IE9, as it is using the prefixed version of css transform, so it should be `-ms-transform: translate(0,0);` Were you testing somehow in IE10 with IE9 mode?

As a conclusion, I will include this if it helps, as `translate3d` is needed anyway for webkit browsers.

**Comment by Rendez** [comment]
I mentioned above I was using `autoprefixer`, which adds `-ms-transform: translate(0,0);` for me. Have you tested in a page with a lot of content? Please take a look on IE9 on our site www.nestpick.com

**Comment by dioslaska** [comment]
`transform: translate(0,0);` is now added in 2.17.0
