### ISSUE TITLE
Scrolling select overlay scrolls the document 

### ISSUE THREAD

**Issue by dsbl411** [acidb/mobiscroll#354]
Hi, 
As you can see in the linked video,  scrolling the bottom of the select overlay scrolls the document. 
http://1drv.ms/1McJuEl
This issue occurs on an iPhone 6 with ios 9.

Thanks. 

Best regards,

**Comment by coldlamper** [comment]
Cannot see the video.

**Comment by dsbl411** [comment]
Cannot reproduce with 2..17. :)
