### ISSUE TITLE
Can the 'Select' components support to custom the text in the <input> after selected?

### ISSUE THREAD

**Issue by n1ce9irl** [acidb/mobiscroll#357]
When I use the 'Select' components,
I wonder if I can custom the text in the < input > after I select one.

For example,
data: [
{ text:'1', value: '1', group: 'one'}, 
{ text:'2', value: '2', group: 'one'}, 
{ text:'1', value: '1', group: 'two'}
]

I hope that when I choose { value: '2', group: 'one'},  I can custom the text and see '2@one' in the  < input >, not just the text '2',
I check the API Documentation but couldn't find out the solution.
Does the mobiscroll support this function to custom the text in the < input > after selected ?

Anyway, useful tools!

**Comment by MRokas** [comment]
Simpliest method would be

    $(ele).mobiscroll().datetime({
        onSelect: function(value,instance) { $(ele).value(value+'@stuff')  }
    });

You should be able get everything you need from instance argument (or arguments[1] )
