### ISSUE TITLE
Limit number of selectable items when multiple select

### ISSUE THREAD

**Issue by dioslaska** [acidb/mobiscroll#358]
Be able to limit the number of items that can be selected, where multiple select is available (select, calendar).

**Comment by dioslaska** [comment]
Added in 2.17.1

**Comment by aschwartz-satcom** [comment]
How do we use it?  I don't see any documentation for this feature on Calendar or Select's API documentation page.

**Comment by dioslaska** [comment]
See here: http://docs.mobiscroll.com/2-17-1/select#!opt-multiple
