### ISSUE TITLE
Improve mousewheel support

### ISSUE THREAD

**Issue by dioslaska** [acidb/mobiscroll#360]
While it works ok with standard mousewheels, it scroll uncontrollably fast with touchpads, especially on OSX, where there is the momentum scroll feature.

**Comment by EnzoEghermanne** [comment]
Any update on this? We are already experiencing this problem in our webapplication and it's really annoying. The scroll (especially on mac) is way too fast.

**Comment by dioslaska** [comment]
Added in 3.0.0
