### ISSUE TITLE
Angularjs Testing

### ISSUE THREAD

**Issue by dhatawesomedude** [acidb/mobiscroll#361]
I use mobiscroll for my Angularjs project, with protractor for tests on selenium. I have failed to test mobiscroll elements in E2E tests, as I cannot access them during the tests. Are there any  guide/examples for testing?

**Comment by szily20** [comment]
For those who are interested in testing with protractor, here is a simple test: 
[test.zip](https://github.com/acidb/mobiscroll/files/142226/test.zip)
