### ISSUE TITLE
jqmBody is lost after .mobiscroll("option", { ... })

### ISSUE THREAD

**Issue by shamank** [acidb/mobiscroll#363]
Hi. I'm using jQuery Mobile (1.4.5) and Mobiscroll 2.17.0 (I think this was not happening in 2.16.1 but I'm not sure).

I'm experimenting an issue with the theme "jqm" after using .mobiscroll() to modify a property of a previously initializated object. My example is based on the calendar component and adding defaults for all mobiscroll objects:

```javascript
$.mobiscroll.setDefaults({
    theme: "jqm"
});

// At this point, ui-body-c class is being added (by default) and it's working as expected
// since I'm using CSS to customize some parts of the component based on this class
// as the parent, like: .ui-body-c .ui-btn.ui-btn-active { ... }
$(el).mobiscroll().calendar();

// After doing this, <div class="dwwr ui-corner-all ui-body-c"> turns into
// <div class="dwwr ui-corner-all ui-body-a"> and as a result I lost my customization
$(el).mobiscroll("option");
```

My quick fix was to include `jqmBody: "c"` as part of the init options for the component:

```javascript
var options = {
    jqmBody: "c"
};

$(el).mobiscroll().calendar(options);
```

Thanks.

**Comment by dioslaska** [comment]
Can't reproduce, the default body swatch for jQuery Mobile 1.4 is 'a', not 'c' (See here http://demo.mobiscroll.com/calendar/basic/jqm#theme=jqm)
