### ISSUE TITLE
CSP Violation under Firefox OS

### ISSUE THREAD

**Issue by cicloon** [acidb/mobiscroll#364]
I'm having this error ```Error: call to Function() blocked by CSP``` when trying to use the datetime plugin within a Firefox OS privileged app. 

Digging into the source code I found ```new Function(...)``` calls which are the ones that throw that violation. Is there any way to make this work under a privileged app?

P.S.: I'm using a trial version build.

**Comment by kovlex** [comment]
Upgrading the license to a production version should fix this error.
