### ISSUE TITLE
Date and time picker

### ISSUE THREAD

**Issue by imevinodh** [acidb/mobiscroll#366]
Hi,

We have recently purchased Date and time picker plugin which works well with our app. However, we are in need of your image plugin as well, to check this we tried the trial version in our app, where it just crash with the Date and time picker plugin.  

Would you please let us know if this can be solved and make both workable in the app? Looking forward your advice.

Thanks and regards,
Vinodh

**Comment by dioslaska** [comment]
Answered on support
