### ISSUE TITLE
es2015 compatible. 

### ISSUE THREAD

**Issue by jamiehutber** [acidb/mobiscroll#385]
I was wondering if it would be possible to enable mobiscroll to be able to use imports. I admit I haven't looked through the code properly to see if it would be an easy thing, but I know it'd be great to be able to include the scripts rather than having to use global on everything.

**Comment by jamiehutber** [comment]
This also ties pretty neatly with webpack support.

**Comment by jamiehutber** [comment]
I have manually added exports to Mobiscroll but clearly I need to look deeper into it as:

**MobiScroll**
``````javascript
line: 3178

const MobiscrollScroller = mobiscroll.react.createComponent ("scroller");
const MobiscrollCalendar = mobiscroll.react.createComponent ("calendar");

export {MobiscrollCalendar, MobiscrollScroller} ;
````
**Console**
``````javascript
mobiscroll.js:3030 Uncaught ReferenceError: optionObj is not defined
``````

**Comment by jamiehutber** [comment]
I have now included react, react-dom and mobiscroll in the html before my webpack bundle. This is working better however I still get the following error:

````javascript
Warning: getInitialState was defined on t, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?
`````

I'm pretty sure this conflicts with es6 classes and not needed to use the getInitialState instead of using this.state in the constructor.

**Comment by dioslaska** [comment]
UMD module loading compatibility added in 3.0.0-beta4
