### ISSUE TITLE
React - Form Switch not redrawing when leaving and reentering view

### ISSUE THREAD

**Issue by jamiehutber** [acidb/mobiscroll#390]
On page load the the switch box will load as expected. However if I leave the page and then come back the switch will just show the plan checkbox.

**Form.js**
`````JavaScript

import Switch from './ui/Switch';

....
	render (){
		return (
			<div>
				<mobiscroll.Form theme="mobiscroll">
                                      <Switch  />
				</mobiscroll.Form>
			</div>
		)
	}
````

**Switch**

`````
//simplified version for example.
import React from 'react';
class Switch extends React.Component {
	render (){
		return (
			<div>
				<input data-role="switch" type="checkbox" />
			</div>
		)
	}
}

export default Switch;

`````

However this will draw correctly if I include the markup from `<Switch />`  directly in the `Form.js` file.

**Comment by jamiehutber** [comment]
I assume this is the when i am rending things, maybe it is because I have the css referenced as a impot tag in my html rather than a css module?

**Comment by andrasz** [comment]
Hi @jamiehutber,

There is a Mobiscroll Switch component that's meant to be used with the Mobiscroll form. You can check out the docs here: https://docs.mobiscroll.com/3-0-0_beta4/react/forms#switch
Also the beta5 release is coming soon, with a lot of react fixes.

**Comment by jamiehutber** [comment]
Thanks mate, that did the trick :) Looking forward to beta5
