### ISSUE TITLE
RTL-related issue of Forms' Switch

### ISSUE THREAD

**Issue by stehlo** [acidb/mobiscroll#393]
The RTL switch is still pointed in the incorrect direction.

Let me explain:
- In the LTR the left side is "turned off" and the right side is "turned on".
- In the RTL the left side should be "turned on" and the right side should be "turned off", i.e. the mirror of the LTR direction.
- However, the RTL switch is still using the direction of LTR, just it is on the opposite side of the screen. This is very confusing for RTL users.

Please compare with, for example, Android's native behaviour.

**Comment by stehlo** [comment]
The issue is present in v.3.0.0-beta5.

**Comment by dioslaska** [comment]
Slider and Progress are also affected: track should be filled from right to left

**Comment by stehlo** [comment]
Apologies for the other report. I haven't realised that I have already filed it. :-\

**Comment by dioslaska** [comment]
Fixed in 3.0.0-beta6
