### ISSUE TITLE
Amazon Fire and Blackberry-related issues of Forms' Switch and Select components

### ISSUE THREAD

**Issue by stehlo** [acidb/mobiscroll#394]
I shall list the issues as they pertain to individual themes. You'll see that the issues vary only slightly and generally they fall into the same categories. Therefore solving them once might resolve all the variations. The issue is present in v.3.0.0-beta5.

### Forms' Select:
- Tapping the Select element crashes the app – themes: **mobiscroll**, **wp**
- Just to compare – the following themes are fine: **material**, **android-holo**, **ios** (they trigger something what looks like a native selector)

### Forms' Switch – issue 1:
- When tapping the label, the switch moves from "off" to "on" (or vice versa) and does **not** change the colour.
- On top of that, it won't return back to "off" (or vice versa) during repeated taps [on the label].
- This happens in the following themes: **android-holo**, **ios**, **material**, **mobiscroll**, **wp**
- Just to compare – the following themes are fine: [none tested]

### Forms' Switch – issue 2:
- When tapping the switch element itself, the switch moves from "off" to "on" (and vice versa) and does **not** change the colour **unless** you zoom the interface enough to be able to tap exactly onto the moving part of the switch(!).
- This happens in the following themes: **android-holo**, **ios**, **material**, **mobiscroll**, **wp**
- Just to compare – the following themes are fine: [none tested]

The latter two issues are closely related and all the affected themes exhibit the same symptoms.

Thank you in advance for looking into this.

**Comment by stehlo** [comment]
I have just discovered that the same issue with Forms' Switches relates also to Amazon Fire (4th generation at least), which is a big market as well. Amazon Fire OS is basically Android.

**Comment by dioslaska** [comment]
Does this happen in the browser or webview (hybrid app), or both?
Could you provide a User Agent string for exact OS and Browser versions?

Thanks

**Comment by stehlo** [comment]
I am working only using WebViews. My apps can't run in browsers.

### Device object of Fire tablet:
cordova: "5.2.2"
isVirtual: false
manufacturer: "Amazon"
model: "KFASWI"
platform: "amazon-fireos"
version: "4.4.2"

### Device object of Blackberry phone:
cordova: "3.8.0"
isVirtual: undefined
manufacturer: "BlackBerry"
model: "Q10"
platform: "blackberry10"
version: "10.3.2.2876"

**Comment by dioslaska** [comment]
navigator.userAgent should be available inside webview as well.

Could you send that as well?

**Comment by stehlo** [comment]
Fire tablet:
Mozilla/5.0 (Linux; Android 4.4.2; KFASWI Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/34.0.0.0 Mobile Safari/537.36

Blackberry phone:
Mozilla/5.0 (BB10; Kbd) AppleWebKit/537.35+ (KHTML, like Gecko) Version/10.3.2.2876 Mobile Safari/537.35+

**Comment by dioslaska** [comment]
Thanks, that helps

**Comment by stehlo** [comment]
Now I can confirm the same issue on **Xgody tablet**.
cordova: "5.2.2"
isVirtual: false
manufacturer: "Allwinner"
model: "Q102A"
platform: "Android"
version: "4.4.4"

So it looks like this problem has to do with Android version 4.4.

On top of the previous issues, I have to report the following one:
- The "checked" dot (or full circle) of Forms' Radios is excentric on both Amazon Fire and Xgody tablets.

**Comment by stehlo** [comment]
OK, so it looks like that these issues were resolved by excluding the custom templates from mobiscroll build.

However, I have now got another new issue related to MenuStrip on Blackberry 10. More on this tomorrow – I shall raise a separate new issue.
