### ISSUE TITLE
MenuStrip Tabs/Navigation underlining not visible on many devices

### ISSUE THREAD

**Issue by stehlo** [acidb/mobiscroll#396]
This is an interesting one.

For the first time I was able to spot the fine grey line under the MenuStrip Tabs/Navigation "buttons", namely on Kindle Fire tablet. This is the only device that displays it.

I knew about this line because I saw it in the Google Chrome's Developer Tools' Screencast. Otherwise, I wouldn't even be aware of its existence.

It looks very nice, by the way, and I would welcome seeing it on each and every device, because it logically splits the top tool bar from the rest of the content.

**Comment by stehlo** [comment]
Not even your demos are showing this line... (I mean "in the browsers".)

**Comment by dioslaska** [comment]
For a better understanding could you perhaps provide a screenshot for this? Thanks

**Comment by stehlo** [comment]
I already forgot what this was about. Let me figure it out and then I update it here again.

**Comment by stehlo** [comment]
No time for this now. Closing the issue until I figure out which template was it related to.
