### ISSUE TITLE
RTL-related issue of Forms' segmented radio buttons

### ISSUE THREAD

**Issue by stehlo** [acidb/mobiscroll#405]
Thank you for the beta6 update.

There is still one issue with the segmented radio buttons, where the rounded corners are on the inside in RTL direction, i.e. not on the outside as they should be. Please see the first screenshot. It is nicely visible on all the three components.

![screenshot1](https://cloud.githubusercontent.com/assets/1798084/19341003/8da17848-9123-11e6-930f-d2463586b1a3.png)

There is one other minor issue. The second segmented component has the second option with one pixel higher box (protruding below). Please see the second screenshot.

![screenshot2](https://cloud.githubusercontent.com/assets/1798084/19341172/4cb64614-9124-11e6-8ecf-78d289a6674c.png)

Please disregard the fact that the MobiScroll Switches and the numberal system are still not localised to Arabic. This won't make any difference for the case at hand.

**Comment by dioslaska** [comment]
Thanks for the report!

Here's a css patch for the Material theme until it's fixed:

    .mbsc-material .mbsc-segmented-item:first-child .mbsc-segmented-content,
    .mbsc-material .mbsc-segmented-item:last-child .mbsc-segmented-content,
    .mbsc-material .mbsc-stepper-minus .mbsc-segmented-content,
    .mbsc-material .mbsc-stepper-plus .mbsc-segmented-content {
        border-radius: 0;
    }
    
    .mbsc-material.mbsc-ltr .mbsc-segmented-item:first-child .mbsc-segmented-content,
    .mbsc-material.mbsc-ltr .mbsc-stepper-minus .mbsc-segmented-content,
    .mbsc-material.mbsc-rtl .mbsc-stepper-plus .mbsc-segmented-content,
    .mbsc-material.mbsc-rtl .mbsc-segmented-item:last-child .mbsc-segmented-content {
        border-top-left-radius: .214286em;
        border-bottom-left-radius: .214286em;
    }
    
    .mbsc-material.mbsc-ltr .mbsc-stepper-plus .mbsc-segmented-content,
    .mbsc-material.mbsc-ltr .mbsc-segmented-item:last-child .mbsc-segmented-content,
    .mbsc-material.mbsc-rtl .mbsc-segmented-item:first-child .mbsc-segmented-content,
    .mbsc-material.mbsc-rtl .mbsc-stepper-minus .mbsc-segmented-content {
        border-top-right-radius: .214286em;
        border-bottom-right-radius: .214286em;
    }

The Android Holo theme however seems ok to me: https://demo.mobiscroll.com/v3/forms#demo=segmented&lang=fa&theme=android-holo

In the Android Holo screenshot I don't see the border radiuses. Maybe some earlier CSS patches are still included?

**Comment by stehlo** [comment]
Thank you, Isti. Much appreciated.

The Android Holo theme doesn't have the "border radii" problem – just the middle item on the second row from the bottom is protruding one pixel down.

**Comment by dioslaska** [comment]
Fixed in 3.0.0
