### ISSUE TITLE
V3 - Scroller laggy on Windows 10 Mobile

### ISSUE THREAD

**Issue by dsbl411** [acidb/mobiscroll#406]
Hi,

I'm currently testing your V3 on Windows 10 Mobile.

With controls that uses your scroller (Date&Time or Select), the scroll experience is really slow and laggy.

On the other hand, the scroll experience is now great with Mobiscroll V2 (cf. #224). 🎉

I'm testing using your demo websites for V2 and V3:
- on a Nokia Lumia 735 
- Windows 10 Mobile version 1607 (10.0.14393.189) (should be up to date)
- Edge 38.14393.189.0 (should be up to date)

Please let me know if you need any further information.

Thanks. 🙂

**Comment by JanPeeters** [comment]
I have the same experience with calendars (not the scrollers) on iOS 9 (iPhone 5S) and Android 6.0.1 (Samsung Galaxy S7). In some cases calendars only open after several seconds.

Unfortunately I wasn't able to test with version 2 as I really don't want to use jQuery on my Angular project.

**Comment by dioslaska** [comment]
We are currently not aware of heavy performance issues on iOS9 or Android 6. Could you share some more information on this? I'd like to see your full initialization code.
If you could put together a working html/js example, or provide a live link to test, it would be even better.

Also, are you experiencing the same [here](https://demo.mobiscroll.com/fullscreen/calendar) for example?

Thanks,
Isti

**Comment by JanPeeters** [comment]
Hi Istvan,

Thank you for your response. I was just copying my code for you when I noticed something that could cause a memory leak:

`invalid: [{start: new Date(1916, 0, 1), end: firstValidDate},{start: lastValidDate, end: new Date(2037, 11, 31)}]`

I changed this to: 

`invalid: [{d: 'w0'}, {d: 'w1'}, {d: 'w2'}, {d: 'w3'}, {d: 'w4'}, {d: 'w5'}, {d: 'w6'}],`
`valid: [{start: firstValidDate, end: lastValidDate}]`

**And now performance is acceptable.**

Is it an idea to make every date invalid by default if only the valid option is used?
Or did I miss an option?

Thanks, Jan

**Comment by dioslaska** [comment]
Thanks for the info! I was about to ask about invalids :)

So yes, having a lot of invalids can slow things down, using start and end is just a shorthand, behind the scenes it creates an array containing dates for every day in between.

In case of many invalids you can consider the following, depending on the use case:

  - just like you did, invalidate all, and pass the few valids. a shorter way to do it:

        invalid: ['w0', 'w1', 'w2', 'w3', 'w4', 'w5', 'w6']

  - use `min` and `max` dates if appropriate
  - update invalids dynamically in the `onMonthLoading` event

        onMonthLoading: function (event, inst) {
             inst.settings.invalid = [ ... ];
        }

**Comment by dsbl411** [comment]
Hi,

Do you have any update on the issue on Windows 10 Mobile?

Thanks 🙂
