### ISSUE TITLE
is there a version that support vuejs?

### ISSUE THREAD

**Issue by 327326724** [acidb/mobiscroll#410]

**Comment by dioslaska** [comment]
We currently don't provide direct integration to Vue.js, but you can use the plain Javascript or jQuery version of Mobiscroll together with Vue.js.
You can update the model value in Mobiscroll's `onSet` event. For model->view binding you can use `$watch` and call the `setVal` method of Mobiscroll to update the picker's value.

**Comment by 327326724** [comment]
thanks

**Comment by jonnywilliamson** [comment]
@dioslaska @327326724 

Would either of you have a very small example of how you do this. I'm a little bit lost with those instructions. Thank you very much.

**Comment by jonnywilliamson** [comment]
As in I can't find any documentation on an `onSet` event for a form component being changed. I can't seem to bind a mobiscroll form component to a v-model data field.

Eg if I have a simple slider and the user moves it, there doesn't seem to be an `onSet` event fired.

**Comment by szily20** [comment]
@jonnywilliamson 

You can see examples on how you can use the Mobiscroll components with Vue.js in the Starter App. There is a slider example too. 

You can find the Vuejs starter app here:  https://mobiscroll.com/starter-apps#vue

**Comment by jonnywilliamson** [comment]
@szily20 Thank you so much for replying. I hadn't seen the vue starter pack.

I'm having a look now and will play with it. 👍
