### ISSUE TITLE
[SOLVED] Safari doesn't work 

### ISSUE THREAD

**Issue by rokity** [acidb/mobiscroll#419]
Hi
I work only with chrome until today, now I watch on safari mobile and desktop and it doesn't work.
It doesn't throw error on console or something else.
This is the screenshot. 
<img width="1280" alt="schermata 2017-01-26 alle 18 05 51" src="https://cloud.githubusercontent.com/assets/6599179/22341728/3370746a-e3f2-11e6-9ec1-379e9a7fd915.png">

Anyone can help me?
I'm using polymer

**Comment by dioslaska** [comment]
It should work fine on Safari as well, from the screenshot it appears that the mobiscroll css is not loaded at all.
Could you send a link, or a zip package, so I can take a look?

Thanks

**Comment by rokity** [comment]
You can download the example here, now doesn't work also in chrome I don't know why.
https://github.com/rokity/mobiscroll-polymer

**Comment by rokity** [comment]
I fix this problem with the style of the mobiscroll plugin. The problem is that: custom style or external style for polymer doesn't work because it needs initialization like [this](https://www.polymer-project.org/1.0/docs/devguide/styling#style-modules). 
So I included the style inside index.html for solve the problem and don't convert every style of mobiscroll plugin.
Thanks
