### ISSUE TITLE
mobiscroll.time/date is not a function?

### ISSUE THREAD

**Issue by sesellis** [acidb/mobiscroll#421]
I'm working on using mobiscroll and following the demos on the website (demo.mobiscroll.com) linked in the readme and I'm unable to get the date or time pickers with the js files provided here. I get "date" or "time" is not a function when trying to do something like this:

`var now = new Date(),
			max = new Date(now.getFullYear() + 100, now.getMonth(), now.getDate());

		
            mobiscroll.date('#test', {
                theme: 'mobiscroll',
				display: 'bottom',
				max: max
                
            });`

Is there something I'm missing? Literally all I've done is clone the project and change the guts of the init method in the example html file to the above. Gets me a .date is undefined error everytime.

Thanks!
Sam

**Comment by dioslaska** [comment]
Hi Sam,

The Date & Time picker is not part of the open source github repo, you need to purchase a license for that on https://mobiscroll.com

This repo contains the Scroller core, which powers the Date & time and other picker components.
