### ISSUE TITLE
style bug under IOS stytem mobile

### ISSUE THREAD

**Issue by wjf444128852** [acidb/mobiscroll#425]
When I click on the input box in IOS and Andrews appear different styles at the bottom，
you can see it at here -http://images.cnblogs.com/cnblogs_com/-walker/998876/o_mobiscroll_bug.jpg

**Comment by dioslaska** [comment]
Could you please specify some more details about this style bug? 
I can't tell from the image.

**Comment by wjf444128852** [comment]
this is style bug in IOS system,
![mobiscroll_bug](https://cloud.githubusercontent.com/assets/16033932/26240545/f4b27bc2-3cb3-11e7-8cd5-5174a6934a17.jpg)

This is online DEMO, you must use the IOS system phone preview, click to select the date will see the style BUG。
http://wjf444128852.github.io/html/joinUs/index.html

**Comment by dioslaska** [comment]
I see that you're using an old version of Mobiscroll (2.5.2). Please upgrade at least to the latest 2.x version (2.17.3).

**Comment by wjf444128852** [comment]
thanks a lot !
