### ISSUE TITLE
Listview navigate won't work with id string

### ISSUE THREAD

**Issue by andrasz** [acidb/mobiscroll#433]
The Angular Listview instance method can take either an id or the item. If the id is provided, the navigate method won't find the listview item and the navigation wont work.

**Comment by dioslaska** [comment]
Fixed in 3.2.4

**Comment by salah00** [comment]
Dear Dioslaska,

can you please give an example on how to implement this navigation with dynamic IDs assigned to the list view item and then passed back to the list view instance to call the navigate method??

**Comment by dioslaska** [comment]
Hi Salah,

Thanks for reaching out.
If you have a license with us, please contact support with some more details on your use case.

Kind regards,
Isti

**Comment by salah00** [comment]
Dear all,
Thanks very much it worked just fine.
Regards,Salah


Sent from Yahoo Mail for iPhone


On Thursday, March 8, 2018, 11:08, Istvan Halmen <notifications@github.com> wrote:


Hi Salah,

Thanks for reaching out.
If you have a license with us, please contact support with some more details on your use case.

Kind regards,
Isti
