### ISSUE TITLE
sorry, how to build the source code ?

### ISSUE THREAD

**Issue by xiaogaofudao** [acidb/mobiscroll#435]
![tim 20170818140519](https://user-images.githubusercontent.com/9261849/29446341-4f6f78a6-841e-11e7-8fce-66d857705a37.png)

thanks a lot

**Comment by ray007** [comment]
From a bit searching it seems this is a problem with `grunt-rollup` after getting a new version of `rollup`.

**Comment by dioslaska** [comment]
package.json modified to update the `grunt-rollup` plugin

**Comment by dioslaska** [comment]
Also, please run `grunt build`, which will also invoke babel to transpile the jsx files for react. That should solve the warning you mentioned.

**Comment by ray007** [comment]
Fresh checkout. Running `grunt build` did nothing to avoid the warning:

```
$ grunt build
Running "babel:dist" (babel) task

Running "less:androidHoloLight" (less) task
>> 1 stylesheet created.

Running "less:iosDark" (less) task
>> 1 stylesheet created.

Running "less:materialDark" (less) task
>> 1 stylesheet created.

Running "less:mobiscrollDark" (less) task
>> 1 stylesheet created.

Running "less:wpLight" (less) task
>> 1 stylesheet created.

Running "less:dev" (less) task
>> 1 stylesheet created.
>> 1 sourcemap created.

Running "less:prod" (less) task
>> 1 stylesheet created.

Running "run:transpile" (run) task

> mobiscroll@3.2.0 transpile J:\devel\jslibs\GIT\mobiscroll
> ngc


Running "rollup:dev" (rollup) task
Warning: Could not resolve '../src/js/scroller.react' from bundles\mobiscroll.react.js Use --force to continue.

Aborted due to warnings.
```

**Comment by dioslaska** [comment]
That's right, the transpilation of `scroller.react.jsx` was missing from the babel configuration file.
Fixed it.

**Comment by ray007** [comment]
Thanks, build now works.
I don't assume there's somewhere an upgrade guide? Dropping the new build result over my 2.17 files doesn't work...
