### ISSUE TITLE
When there are multiple scroller in wheels, how do I get which box is currently sliding in scroller?

### ISSUE THREAD

**Issue by RodeyManager** [acidb/mobiscroll#437]
When there are multiple wheels in my scroller, how should I determine which wheels boxlist (className:  '_.mbsc-sc-whl-w_' ) I'm currently sliding, and how element gets the current choice in onChange?

**Comment by RodeyManager** [comment]
[image preview](http://7jpr3b.com1.z0.glb.clouddn.com/mobiscroll-scroller.png)

**Comment by dioslaska** [comment]
You can use the [validate](https://docs.mobiscroll.com/scroller#event-validate) event for that, it will also be called on every change, and on initial show as well. It also receives the index of the changed wheel, and an array containing the selected items on every wheel.

**Comment by RodeyManager** [comment]
Thank you very much. The problem has been solved
