### ISSUE TITLE
kitchen sink example fails to find css and js files

### ISSUE THREAD

**Issue by cepm-nate** [acidb/mobiscroll#441]
It looks for these two files:

    <link href="../../dist/css/mobiscroll.css" rel="stylesheet">
    <script src="../../dist/js/mobiscroll.javascript.js"></script>

which do not exist.

Is there any chance we could get a compiled dist folder again, with those files in it so the examples would work?

Thanks.

**Comment by dioslaska** [comment]
Please run the `npm install` and `grunt build` commands to generate the dist folder.
Added a README file as well to the kitchensink example folder.
