### ISSUE TITLE
OPPO R9s Plus显示当天时间不对

### ISSUE THREAD

**Issue by Jeijie** [acidb/mobiscroll#442]
oppo R9s选择日期时间时，默认显示的日期是昨天的时间，但是它真正的时间是当天的时间。其他手机默认的是当天时间，真正的时间也是当天时间。

OPPO R9s Plus
mobiscroll 3.0.0
![c w8h 1f udy4o om fq6](https://user-images.githubusercontent.com/9338052/33866252-67a1ce02-df30-11e7-9790-ba13f91d6f0e.png)

**Comment by dioslaska** [comment]
Please try upgrading to latest stable version (3.2.6) and see if it still happens.

**Comment by Jeijie** [comment]
thank you
