### ISSUE TITLE
Keyboard support broken?

### ISSUE THREAD

**Issue by lougreenwood** [acidb/mobiscroll#447]
Seems that the keyboard support listed on accessibility page is not working?

For example, I can't use esc to close a popover ("bubble") or keyboard to control the control.

https://docs.mobiscroll.com/javascript/accessibility

Mobiscroll 4.2.3
Safari 11.1

**Comment by dioslaska** [comment]
I could not reproduce this so far.
Please check [here](https://demo.mobiscroll.com/fullscreen/datetime/date). Esc correctly closes the popover in Safari as well.
If the problem persists, please send an example / link with steps to reproduce, and / or screen recording.

Thanks!

**Comment by dioslaska** [comment]
Any details here?
