### ISSUE TITLE
Events Calendar - scroll on events area not on entire control.

### ISSUE THREAD

**Issue by ganySA** [acidb/mobiscroll#452]
Hi

I am using the events calendar in a ionic application, when the events are longer than the view port the entire content area scrolls, is there a setting which allows for the top of the calendar to be fixed at the top and that the events area scrolls?

See attached image.... when scroll i would like only the inner area of the control with events to scroll - the green arrow, what ends up happening is the red area scrolls which then cuts off the header...
Another way of explaining is to have the calendar part of the control "fixed" to the top of the screen.

![image](https://user-images.githubusercontent.com/3189206/43999668-5e8c635e-9e11-11e8-9231-ed6990e9fa74.png)

**Comment by dioslaska** [comment]
This is not yet built in, but you can find possible solution in [this forum thread](https://forum.mobiscroll.com/t/scroll-event-to-top-of-list/50).

**Comment by dioslaska** [comment]
Added in 4.6.0 - see the `scrollable` property of the [view](https://docs.mobiscroll.com/eventcalendar#opt-view) -> eventList setting
