### ISSUE TITLE
How can I add sub label below headerText in Scroller

### ISSUE THREAD

**Issue by PhiHoang** [acidb/mobiscroll#453]
I have a problem, what property which help me add sub label below headerText of wheels in Scroller
like this: https://pictshare.net/saaj5bijpz.jpg

My current mobiscroll version: mobiscroll-angular@4.0.0
Angular version: 4.4.6

Thanks very much !

**Comment by dioslaska** [comment]
Please move this to the [forum](https://forum.mobiscroll.com/).

Thanks!
