### ISSUE TITLE
Issue on calendar when setting min/max dates

### ISSUE THREAD

**Issue by apopat86** [acidb/mobiscroll#456]
Since 1st Jan 2019, I'm now unable to select dates/times on the calendar control whilst I have a min and/or max date set (using mobiscroll 4.5.0 on Angular)

These are my settings for the control to replicate:
`  datePickerSettings = {
    theme: 'mobiscroll',
    display: 'bubble',
    showLabel: false,
    yearChange: false,
    showScrollArrows: true,
    controls: ['calendar','time'],
    dateFormat: 'D d',
    timeFormat: 'H:00',
    min: new Date(2018, 11, 5, 10,0,0,0),
    max: new Date()
  };`

As a result, when trying to click on any active day, the day above it gets selected instead (e.g. in the screenshot, I click on 25th Dec 2018 and instead 18th Dec 2018 gets selected)

![image](https://user-images.githubusercontent.com/20026554/50573006-5194c980-0dc3-11e9-8dd3-3e86dca826ef.png)

**Comment by dioslaska** [comment]
I don't know the exact cause of the issue, but it looks like it's related to the `dateFormat` setting: if no year is present in the `dateFormat`, the dates are parsed incorrectly.

**Comment by dioslaska** [comment]
Fixed in 4.5.3
