### ISSUE TITLE
jQuery Calendar undefined instance

### ISSUE THREAD

**Issue by TiviT** [acidb/mobiscroll#457]
Lib version used 3.2.0

```
$(this).mobiscroll().calendar({
    theme: 'ios',
    lang: lang,
    display: 'bottom',
    dateFormat: 'dd.mm.yy',
    min: min,
    max: max,
    onBeforeShow: function(event, inst) {
        $(".elem").blur();
    },
    onDayChange: function(event, inst) {
        inst.setVal(event.date, true)
    },
    onBeforeClose: function (event, inst) {
        if (!inst.getVal() && event.button == 'set') {
            return false;
        }
    },
    defaultValue: defaultValue,
});
```

Logged error: StackTrace: TypeError: null is not an object (evaluating ‘inst.getVal’); Plattform: iOS; Device: iPhone10,4; OS version: 11.4.1;

P.S checked lib change log(3.2.X and 4.X) an didn’t found relevant fixes

**Comment by dioslaska** [comment]
Could not reproduce this.

More details here: https://forum.mobiscroll.com/t/calendar-undefined-instance/250/6
