### ISSUE TITLE
When i use mobiscroll range calendar, second date is not looking in proper format.  something like this (&#68;im. 24 Mars)

### ISSUE THREAD

**Issue by adnan50** [acidb/mobiscroll#460]
I am using French language in mobicalendar 
` $(".demo-mobile").mobiscroll().range({
         
dateFormat: 'D d M',
startInput: '#start',
        endInput: '#end',
        display: 'inline',  
       // autoCorrect:true,
        touchUi:true,
    });`

**Comment by dioslaska** [comment]
Thanks for reporting, this is an issue inside the french translation files. Will be fixed in 4.6.1.
Until than you can use the following drop-in fix (before any component initialization):

    mobiscroll.i18n.fr.dayNames[0] = 'Dimanche';
    mobiscroll.i18n.fr.dayNamesShort[0] = 'Dim.';
    mobiscroll.i18n.fr.dayNamesMin[0] = 'D';

**Comment by dioslaska** [comment]
Fixed in 4.6.1
