### ISSUE TITLE
Optionally display Start and End Times in event bubble

### ISSUE THREAD

**Issue by ot-dtd** [acidb/mobiscroll#465]
In the Event Calendar, when the event list bubble is opened, it lists only the start time of an event or All-Day. It would be useful to allow the option of displaying the start and end times, as well as overriding the All-Day function for cross midnight events.

**Comment by dioslaska** [comment]
Can be done with custom event template ([renderEvent](https://docs.mobiscroll.com/eventcalendar#opt-renderEvent) / [eventTemplate](https://docs.mobiscroll.com/angular/eventcalendar#opt-eventTemplate)).
