### ISSUE TITLE
Typescript definitions?

### ISSUE THREAD

**Issue by paddotk** [acidb/mobiscroll#468]
Hi,

I was wondering if there is any Typescript definitions support for the React version of Mobiscroll components? I couldn't find anything about this, only that it's available for the jQuery version on the Mobiscroll website. I checked the DefinitelyTyped lib list as well, but that list is so long that Github can only manage to show a small part of it :(

**Comment by dioslaska** [comment]
Yes, there are Typescript definition files for React as well, here's the entry point for the typings:

https://github.com/acidb/mobiscroll/blob/master/src/js/frameworks/react.d.ts
