### ISSUE TITLE
Could not be resolved to an NgModule class with Angular ivy

### ISSUE THREAD

**Issue by Ketec** [acidb/mobiscroll#470]
Send this bug to the support over a month ago - it's the only thing holding back enabling Ivy on the project.
It was supposedly passed on  - but I do not see a related ticket in here. So not sure if it got lost or not.

Because MbscModule return value is not a valid ngModule definition, it causes fatal errors.
It fails because the return value is undefined.
function registerNgModuleType(ngModuleType)
All that's required is ivy enabled and using MbscModule in any of the app's modules.

**Comment by dioslaska** [comment]
So far it looks like this is an issue with Ivy. We reported it to the Angular team: https://github.com/angular/angular/issues/30972#issuecomment-520467146

**Comment by dioslaska** [comment]
Starting from 4.9.0 Ivy is supported, but only in the 9.x version of Angular (current version being v9.0.0-rc.4). 

In Angular 8.x the `ngcc` compiler has some bugs and cannot compile some of the Mobiscroll components. 

In 9.x `ngcc` still has some bugs when used with minified es5 files, but we added workarounds to make it work.
