### ISSUE TITLE
4.8.4 - Inifinite JS refreshing on calendar

### ISSUE THREAD

**Issue by stabback** [acidb/mobiscroll#472]
Hello,

I think I've stumbled on a bug.  Reproduction repo: https://github.com/stabback/mobiscroll-calendar-responsive-loop-reproduction

An infinite JS loop is caused when initializing a calendar with the following options:

```js
{
    display: 'inline',
    responsive: {
        large: {}
    }
}
```
Any other options can be provided, but setting the `responsive` attribute alongside `display: 'inline'` causes this loop.

The README in the sample repo has more information.

**Comment by dioslaska** [comment]
Fixed in 4.8.5
