### ISSUE TITLE
Angular doensn't compile with mobiscroll in version 9 rc.8 and newer with Ivy enabled.

### ISSUE THREAD

**Issue by luthor77** [acidb/mobiscroll#475]
This error happens:
> ERROR in The target entry-point "@mobiscroll/angular" has missing dependencies:
> - ../src/js/i18n/pt-BR
> - ../src/js/themes/mobiscroll-dark
> - ../src/js/themes/material
> - ../src/js/themes/material-dark
> - ../src/js/themes/auto-theme

I don't know if this is a problem with Angular or Mobiscroll, and I don't know how to create an repository using the mobiscroll paid version.

With ivy disabled, it compiles, but the ng test gives the same error.

I'd be grateful with any help.

**Comment by dioslaska** [comment]
I tried with the latest 4.10.2 version with angular 9.0.0-rc.8 and 9.0.0-rc.11 and it compiled for me.

Could you please share the mobiscroll version you were using?

**Comment by luthor77** [comment]
I'm using 4.10.2, and I just tested now with angular 9.0.0-rc.11. Same error.

**Comment by luthor77** [comment]
This is my package.json. I tried cleaning node_modules and cache, but nothing works.

> {
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build": "ng build",
        "build:prod": "ng build --prod --outputPath=dist/prod",
        "tests": "ng test",
        "test:nowatch": "ng test --watch=false --codeCoverage=true",
        "lint": "ng lint",
        "e2e": "ng e2e",
        "postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"
    },
    "private": true,
    "dependencies": {
        "@angular/animations": "~9.0.0-rc.11",
        "@angular/cdk": "^9.0.0-rc.8",
        "@angular/common": "~9.0.0-rc.11",
        "@angular/compiler": "~9.0.0-rc.11",
        "@angular/core": "~9.0.0-rc.11",
        "@angular/forms": "~9.0.0-rc.11",
        "@angular/material": "~9.0.0-rc.8",
        "@angular/material-moment-adapter": "^9.0.0-rc.8",
        "@angular/platform-browser": "~9.0.0-rc.11",
        "@angular/platform-browser-dynamic": "~9.0.0-rc.11",
        "@angular/router": "~9.0.0-rc.11",
        "@fullcalendar/angular": "^4.3.1",
        "@fullcalendar/core": "^4.3.1",
        "@fullcalendar/daygrid": "^4.3.0",
        "@fullcalendar/interaction": "^4.3.0",
        "@fullcalendar/timegrid": "^4.3.0",
        "@ngxs-labs/data": "^2.4.1",
        "@ngxs/devtools-plugin": "^3.6.1",
        "@ngxs/router-plugin": "^3.6.1",
        "@ngxs/storage-plugin": "^3.6.1",
        "@ngxs/store": "^3.6.1",
        "@types/socket.io-client": "^1.4.32",
        "moment": "^2.24.0",
        "moment-timezone": "^0.5.27",
        "ngx-mask": "^8.1.7",
        "normalize.css": "^8.0.1",
        "rfdc": "^1.1.4",
        "rxjs": "~6.5.4",
        "socket.io-client": "^2.3.0",
        "zone.js": "~0.10.2",
        "@mobiscroll/angular": "file:./src/lib/mobiscroll-package/mobiscroll-angular-4.10.2.tgz"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "^0.900.0-rc.10",
        "@angular/cli": "~9.0.0-rc.10",
        "@angular/compiler-cli": "~9.0.0-rc.11",
        "@angular/language-service": "~9.0.0-rc.11",
        "@types/jasmine": "~3.5.1",
        "@types/jasminewd2": "~2.0.8",
        "@types/node": "^13.5.0",
        "codelyzer": "^5.2.1",
        "jasmine-core": "~3.5.0",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~4.4.1",
        "karma-chrome-launcher": "~3.1.0",
        "karma-coverage-istanbul-reporter": "~2.1.1",
        "karma-jasmine": "~3.1.0",
        "karma-jasmine-html-reporter": "^1.5.1",
        "protractor": "~5.4.2",
        "ts-node": "~8.6.2",
        "tslint": "~6.0.0",
        "typescript": "~3.7.5"
    }
}

**Comment by dioslaska** [comment]
Thanks for the details!

Indeed, I tested this with the pre-built npm package, and I see that you were using the dynamic one downloaded from our website.
I tested it with the downloaded package and it happened to me as well. This is actually an Ivy issue which was introduced in one of the rc versions.
To overcome this, I modified our download builder to remove the js file references from the d.ts file.

To fix it in your project, please download the package again, and run the `mobiscroll config angular --no-npm` command again.

**Comment by luthor77** [comment]
Thanks for the fast fix, but now I'm getting an error with the installation.

> Mobiscroll configuration started.
>
> No mobiscroll js/css files were found in your project's src/lib/mobiscroll folder.
>
> Please make sure to extract the downloaded Mobiscroll package, then grab the lib folder and copy it into src folder of your app!

I'm using @mobiscroll/cli@1.3.4

**Comment by dioslaska** [comment]
I could not reproduce this. Please contact the support from your licensed account and send the downloaded package to see what could be wrong.

**Comment by luthor77** [comment]
Ok. Thank you again.
