### ISSUE TITLE
Error compiling in Angular 10

### ISSUE THREAD

**Issue by luthor77** [acidb/mobiscroll#478]
I'm getting an error compiling the Angular 10:
![Anotação 2020-06-30 171421](https://user-images.githubusercontent.com/31356395/86173165-ef22a380-baf5-11ea-9343-53ca703a91bd.png)

I was waiting a fix, but the latest version said the necessary changes were made: 
"We made the necessary type changes for compatibility with Angular 10"

My current version:
![Anotação 2020-06-30 172034](https://user-images.githubusercontent.com/31356395/86173262-17aa9d80-baf6-11ea-868c-4af67aea838e.png)

**Comment by dioslaska** [comment]
Our download builder needed some more fixes when generating the package.
Please download and run the config command again.

**Comment by luthor77** [comment]
Thanks, no errors now.
