### ISSUE TITLE
(Bye Security Trial) Hello Security 

### ISSUE THREAD

**Issue by alexiagaray** [acidb/mobiscroll#479]
slice ur text of trials (bad idea use local security , sorry)

![Снимок экрана 2020-07-26 в 7 09 37](https://user-images.githubusercontent.com/56755652/88471269-ff207e00-cf0f-11ea-89dd-cb692458c2f4.png)

@johnnyshields  @torhovland  @dahool  @yetty  @char0n

**Comment by char0n** [comment]
What exactly is this about please?

**Comment by dioslaska** [comment]
The trial is for testing purposes only and beside the "TRIAL" captions also has a built-in server-side validation.
