### ISSUE TITLE
Non-touchUI Select option overflow issue

### ISSUE THREAD

**Issue by ericmoolin** [acidb/mobiscroll#480]
I believe there is an issue when trying to display '4' or any other even number of rows on a non-touchui select element. The options overflow out of the popup.

![image](https://user-images.githubusercontent.com/20781700/93810016-e7f5c800-fc02-11ea-8e25-0c696c2c04f9.png)
![image](https://user-images.githubusercontent.com/20781700/93810220-2ab7a000-fc03-11ea-89d1-631927c9c244.png)

Displaying '3', '5' and other odd numbers display fine.

![image](https://user-images.githubusercontent.com/20781700/93810314-4de24f80-fc03-11ea-91fa-9d2582b6d509.png)
![image](https://user-images.githubusercontent.com/20781700/93810341-59ce1180-fc03-11ea-9115-ee16e0e358a4.png)

**Comment by mattmogford-alcumus** [comment]
I have come across this exact same thing!
This has to be more of a common issue.
It looks like it is trying to center the 'middle' row in the popup, but because there is an even number there is no middle row and we lose half of the top row.

**Comment by dioslaska** [comment]
Fixed in 4.10.9
