### ISSUE TITLE
I'm getting error after I change the package from angular to angular-lite

### ISSUE THREAD

**Issue by captainmio** [acidb/mobiscroll#482]
This project was only passed to me from a developer who already left the company. Before it uses **@mobiscroll/angular** package and I decided to update it to **@mobiscroll/angular-lite**. I really don't have any background with angular and I only know VUE JS

![image](https://user-images.githubusercontent.com/16423723/107610923-c06cce00-6c7d-11eb-8b15-9ed914aa99ff.png)

I'm getting error on the following line of codes, I've check the docs and they have the same code so I'm not sure why I'm getting these errors

my current node version is 10.12.0

**Comment by dioslaska** [comment]
The calendar is part of our commercial package, so it's not present in the lite version. If you or the company owns a commercial license, please contact support@mobiscroll.com to sort this out.
