### ISSUE TITLE
Datepicker scroll freeze issue

### ISSUE THREAD

**Issue by jinwonpark1** [acidb/mobiscroll#483]
There seems to be a recurring bug regarding date picker.

The calendar seems to be freezing when
1) I pick any date from month in the future(ex. March)
<img width="404" alt="스크린샷 2021-02-19 오후 6 47 08" src="https://user-images.githubusercontent.com/48266294/108487966-2ba04b00-72e3-11eb-96fb-5c4c477f59bd.png">

2) I click shaded grey area(dates from previous month) to go back 1 month.
<img width="398" alt="2" src="https://user-images.githubusercontent.com/48266294/108488056-483c8300-72e3-11eb-80d9-9976cac9c481.png">

3) When I try to go back to next month. (ex. March again)

<img width="402" alt="스크린샷 2021-02-19 오후 6 47 30" src="https://user-images.githubusercontent.com/48266294/108488674-0102c200-72e4-11eb-8886-665ed7211585.png">

The right arrow button does not work. Also, swiping the calendar does not work.

**Comment by dioslaska** [comment]
Fixed in 5.4.0
