### ISSUE TITLE
Mobiscroll on angular doesn't respect returnFormat parameter

### ISSUE THREAD

**Issue by jpike88** [acidb/mobiscroll#487]
I set returnFormat to 'moment':

<img width="390" alt="Screenshot 2021-06-11 at 12 25 56 PM" src="https://user-images.githubusercontent.com/9585787/121635287-2d6b6580-cab0-11eb-94d1-80f468ae7cc9.png">

Yet when calling getVal in the onClose callback, I get a Date object.

<img width="276" alt="Screenshot 2021-06-11 at 12 26 29 PM" src="https://user-images.githubusercontent.com/9585787/121635329-407e3580-cab0-11eb-9ab1-1399e87f6e0c.png">

**Comment by andrasz** [comment]
@jpike88 In order for the moment return format to work, you need to pass the moment library to the datepicker. Currently this can only be done via the `[options]` attribute, but we will include a fix for the next version so it can be passed via the [moment] attribute as well.

ex.:

```tsx
import * as moment from 'moment';

@Component({...})
export class MyComponent {
  theOptions = {
    moment: moment,
    returnFormat: 'moment',
  };
  // ...
}
```

and then in your template:
```html
<mbsc-datepicker [options]="theOptions"></mbsc-datepicker>
```

**Comment by jpike88** [comment]
this worked, moment now works in the library fine
