### ISSUE TITLE
Mobiscroll CLI and configure Ionic app doesn't work

### ISSUE THREAD

**Issue by ihorbond** [acidb/mobiscroll#489]
Following tutorial here 
https://docs.mobiscroll.com/5-7-2/react/getting-started
Executing this step 
`mobiscroll config ionic --version=5`
throws following error:

Could not install Mobiscroll.

Error: Command failed: npm install @mobiscroll/react@5.7.2 --save
npm ERR! code ETARGET

**Comment by dioslaska** [comment]
If still an issue, please contact support@mobiscroll.com
