### ISSUE TITLE
v5.9.1 Event Calendar issue

### ISSUE THREAD

**Issue by tamartin1967** [acidb/mobiscroll#492]
setOptions method no longer works, getting error that it is not a function. If I revert to earlier version it works.  Please see the below code for usage:

        function GetTechCalendarData(LaborPK) {
            $.ajax({
                url: "TechCalendar.aspx/GetTechCalendarData",
                type: "post",
                dataType: "json",
                contentType: "application/json;charset=utf-8",
                data: '{ LaborPK: "' + LaborPK + '" }',
                success: function (result) {
                    // notify the data source that the request succeeded
                    var data = JSON.parse(result.d);
                    var inst = $('#techCalendar').mobiscroll5('getInst');
                    console.log(inst);
                    inst.setOptions({
                        labels: data.Labels
                    });
                    inst.setEvents(data.Events);
                },
                error: function (result) {
                    // notify the data source that the request failed
                    console.log(result);
                }
            })
        }

**Comment by dioslaska** [comment]
I could not reproduce this with version 5.9.1. 
Please send a working example reproducing the issue to support@mobiscroll.com, using the email address of the licensed account.

**Comment by dioslaska** [comment]
Closed due to inactivity.
