### ISSUE TITLE
ionChange not triggered version 5 and ionic 6

### ISSUE THREAD

**Issue by obentoumi** [acidb/mobiscroll#495]
1. The ionChange is not triggered when I'm using the version 5.13.4 into the angular-ionic project (angular 13 & ionic 6).
Here is a html template I'm using for the demo 
<ion-content>
    <ion-item>
        <ion-label position="floating">Birthday</ion-label>
        <ion-input [(ngModel)]="myBirthday" mbsc-datepicker (ionChange)="onDateChange($event)"></ion-input>
    </ion-item>
    <ion-item>
        <ion-label position="floating">Name</ion-label>
        <ion-input [(ngModel)]="name" (ionChange)="onDateChange($event)"></ion-input>
    </ion-item>
</ion-content>

2. Also, the rendering of the ion-label with floating position is overlapped with  the ion-input and mbsc-datepicker (please see attached screenshot)
<img width="356" alt="Screenshot 2022-01-20 at 08 49 43" src="https://user-images.githubusercontent.com/73524466/150301433-f21843e7-0c32-436b-b2cf-f97aea8fcc9a.png">

**Comment by dioslaska** [comment]
Fixed in 5.15.1
