### ISSUE TITLE
Adjust Custom HTML structure In mobiscroll - Mobile Date Picker In Jquery

### ISSUE THREAD

**Issue by memojtabazamani** [acidb/mobiscroll#496]
Hello
How can we add different headers or sections to the component?
For example, I want to add a header to my data body
Or specify a container for rendering with a personal structure?
How is this possible?

**Comment by dioslaska** [comment]
Ask support questions on the [forum](https://forum.mobiscroll.com) or contact support, if you have a commercial license.
