### ISSUE TITLE
Module ‘”@mobiscroll/angular”’ has no exported member ‘MbscCalendarEvent’

### ISSUE THREAD

**Issue by anounbobo** [acidb/mobiscroll#504]
When trying to import MbscCalendarEvent, I got the following error message:

Module ‘"@mobiscroll/angular"’ has no exported member ‘MbscCalendarEvent’

import { MbscCalendarEvent } from ‘@mobiscroll/angular’;

Mobiscroll version: 4.10.10

**Comment by dioslaska** [comment]
It's only available from version 5.
