### ISSUE TITLE
[Popup] Anchored Popup failing in React 18 strict mode

### ISSUE THREAD

**Issue by HillaryManning** [acidb/mobiscroll#506]
## Issue
Anchored Popover element critically fails with React 18 strict mode.

I started seeing this issue after updating a project to React 18.2.0 and Mobiscroll from 5.17.1 to 5.18.1.
<img width="1251" alt="Screen Shot 2022-08-12 at 12 42 09 PM" src="https://user-images.githubusercontent.com/16481506/184414123-ef3f0fa7-a89e-45b1-a676-ff4f9df56974.png">

I reviewed the Mobiscroll 5.18.1 release notes and noticed this bug-fix
<img width="647" alt="Screen Shot 2022-08-12 at 12 45 24 PM" src="https://user-images.githubusercontent.com/16481506/184414507-9fa0edf8-05d8-4e1a-a796-0f90fa5b3f77.png">

I tried turning off strict mode and now things work as expected.

## Expected Behavior
Anchored Popover element works as usual with strict mode on.

**Comment by dioslaska** [comment]
Could not reproduce this, could you share the relevant code please?
