### ISSUE TITLE
Timeline schedule slot not displaying properly if schedule card has dynamic height

### ISSUE THREAD

**Issue by webdevsyd** [acidb/mobiscroll#507]
I am currently using the `Timeline` component is there a way that the schedule card is properly rendered if the height is dynamic? Currently our component height is dependent on the contents inside it. I am encountering an issue wherein there are white spaces if the schedule slot has a different height

![Screen Shot 2022-08-31 at 3 16 25 PM](https://user-images.githubusercontent.com/15810023/187810318-329ac447-ced0-4230-b6a2-c82c8315f6cd.png)

Another example is the schedule slot overlapping on page loads because the height is different for every schedule slot.
![Screen Shot 2022-09-01 at 8 57 56 AM](https://user-images.githubusercontent.com/15810023/187810238-e43028d6-03a1-44e9-9fee-95051101f86e.png)
0751.png)

How can I fix this?

**Comment by dioslaska** [comment]
Having different height for events is currently not supported.

**Comment by dioslaska** [comment]
Variable event height support added in [v5.30.0](https://mobiscroll.com/releases#product-v5300)
