### ISSUE TITLE
Scheduler multiple timezones shows wrong times for certain timezones - React

### ISSUE THREAD

**Issue by amitk7407** [acidb/mobiscroll#510]
While using "multiple timezones" feature of Mobiscroll Scheduler, the time mapping for the timezones are not correct.
Eg -> 
    `<Eventcalendar
            data={events}
            view={{
                "schedule": {
                  "type": "day",
                  "size": 7,
                  "allDay": false,
                  "timezones": [
                      {
                         "timezone": "Africa/Bangui",
                         "label": "You UTC+01:00"
                      },
                      {
                         "timezone": "Pacific/Midway",
                         "label": "Client UTC-11:00"
                      }
                  ]
              }
          }}
    </EventCalendar>`

Here the UI is   
![bangui](https://user-images.githubusercontent.com/20415001/212000673-0c2581a9-a6a6-4e3d-8444-ce18527b10e1.PNG)

But when I use,
    `<Eventcalendar
            data={events}
            view={{
                "schedule": {
                  "type": "day",
                  "size": 7,
                  "allDay": false,
                  "timezones": [
                      {
                         "timezone": "Africa/Algiers",
                         "label": "You UTC+01:00"
                      },
                      {
                         "timezone": "Pacific/Midway",
                         "label": "Client UTC-11:00"
                      }
                  ]
              }
          }}
    </EventCalendar>`
then the UI is 
![algiers](https://user-images.githubusercontent.com/20415001/212000694-4f198fd8-9e89-48e0-81cc-60943672f803.PNG)

Here, both the timezones are GMT+1 but if you compare the UIs, there is 1 hour shift in case of Africa/Algiers. This is happening for some other timezones as well.

Same issue with London timezone with view settings:
`{
    "schedule": {
        "type": "day",
        "size": 7,
        "allDay": false,
        "timezones": [
            {
                "timezone": "Europe/London",
                "label": "You UTC+00:00"
            },
            {
                "timezone": "Pacific/Midway",
                "label": "Client UTC-11:00"
            }
        ]
    }
}`
![london](https://user-images.githubusercontent.com/20415001/212000714-1832ea40-2cd2-4379-94a1-4632b18b53d6.PNG)

**Comment by profitsky** [comment]
is there any progress on this, I am struggling with the same DTS problem

**Comment by dioslaska** [comment]
We fixed this is [v5.32.1](https://mobiscroll.com/releases#product-v5321)

However it won't be perfect on views other than single day, because on DST days the times are different from the rest of the days in the view.
