### ISSUE TITLE
Eventcalendar.renderScheduleEventContent no longer works when function returns JSX.Element (broke @mobiscroll/react v.5.22.0)

### ISSUE THREAD

**Issue by thhermansen** [acidb/mobiscroll#513]
We have the following code:

```tsx
    import { Eventcalendar } from '@mobiscroll/react';

    <EventCalendar
      data={calendarEvents}
      renderScheduleEventContent={(event) => {
        return <span>{event.title}</span>;
      }}
      view={{
        timeline: {
          type: 'week',
        },
      }}
    />
```

Which renders this, without the `event.title`: 

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/92300/223415554-abf7602e-1d6f-4eb9-9318-e00426fc7b12.png">

In version v.5.21.2 this would rendered the `event.title` above the event's time. If we alter the code a bit so it returns only a string:

```tsx
    import { Eventcalendar } from '@mobiscroll/react';

    <EventCalendar
      data={calendarEvents}
      renderScheduleEventContent={(event) => {
        return event.title;
      }}
      view={{
        timeline: {
          type: 'week',
        },
      }}
    />
```

We get:

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/92300/223415879-6cd5a594-9cbd-473c-980e-595f1fbd755b.png">

Which is more in line with what we expect, where the title of the event is rendered.

--------------

Btw, we can inject HTML by returning a string, but this is obviously not something we want to do:

```tsx
    import { Eventcalendar } from '@mobiscroll/react';

    <EventCalendar
      data={calendarEvents}
      renderScheduleEventContent={(event) => {
        return `<span style="color: red;">${event.title}</span>`;
      }}
      view={{
        timeline: {
          type: 'week',
        },
      }}
    />
```

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/92300/223416334-a4133957-7e98-4184-a9ef-f20aa1bda14e.png">

**Comment by dioslaska** [comment]
Fixed in v5.22.3
