### ISSUE TITLE
Feature Request: Adding a custom element inside EventCalendar data prop

### ISSUE THREAD

**Issue by codev-dean** [acidb/mobiscroll#514]
As of right now, there's no way to accept custom elements in `@mobiscroll/react: ^5.22.0` (however, if there is a way, please let me know).

For example, the feature request is something like this:
![feature-req](https://user-images.githubusercontent.com/121065326/226801971-304f6397-5ead-4185-a0d9-3436b0f5d17a.png)

As you can see from the image, the ones that are labelled as `el#1` and `el#2` are the custom elements. We want to be able to add those via props called `customElement` or something relevant. Basically, it adds a `ReactNode` so we can customize it however we want to look.

**Comment by dioslaska** [comment]
This is possible using the custom render functions, [renderScheduleEvent](https://docs.mobiscroll.com/react/eventcalendar#opt-renderScheduleEvent) or [renderScheduleEventContent](https://docs.mobiscroll.com/react/eventcalendar#opt-renderScheduleEventContent), which can return any jsx markup.
Example: https://demo.mobiscroll.com/react/scheduler/customizing-events#

**Comment by codev-dean** [comment]
> This is possible using the custom render functions, [renderScheduleEvent](https://docs.mobiscroll.com/react/eventcalendar#opt-renderScheduleEvent) or [renderScheduleEventContent](https://docs.mobiscroll.com/react/eventcalendar#opt-renderScheduleEventContent), which can return any jsx markup. Example: https://demo.mobiscroll.com/react/scheduler/customizing-events#

Thanks for this  @dioslaska!
