### ISSUE TITLE
clickToCreate single not working on mobile

### ISSUE THREAD

**Issue by JosepSalvat** [acidb/mobiscroll#516]
Hello!
I'm using the <Calendar> component and it works like a charm on desktop. But for some reason I saw that the clickToCreate it doesn't work on mobile.

There's something that I can do to try to get it work? On click (finger) I want to create an event, for now I've the double clickToCreate but it's not looking good :(

Thanks!

**Comment by dioslaska** [comment]
The `clickToCreate` option intentionally only works on desktop, as stated in the [docs](https://docs.mobiscroll.com/javascript/eventcalendar#opt-clickToCreate).

In touch environment a long tap should be used to create a new event and it is controlled with the [dragToCreate](https://docs.mobiscroll.com/javascript/eventcalendar#opt-dragToCreate) option.
