### ISSUE TITLE
A problem in google calendar integration 

### ISSUE THREAD

**Issue by semah1213** [acidb/mobiscroll#519]
hi everyone,
im trying to integrate the google calendar for my react app using Mobiscroll component, first i tried ‘npm i @mobiscroll/calendar-integration’ i got an error “403 403 Forbidden - GET https://npm.mobiscroll.com/@mobiscroll%2fcalendar-integration - no suitable version exists In most cases, you or one of your dependencies are requesting a package version that is forbidden by your security policy, or on a server you do not have access to.”
the i tried to import googleCalendarSync from @mobiscroll/react and i found the calendar-integration module there i imported it in my component and everything looked fine but when i start my app i got this error “Uncaught TypeError: Cannot read properties of undefined (reading ‘init’)” here “googleCalendarSync.init({” is there any possible solution for this problem i would be so grateful
thank you

**Comment by dioslaska** [comment]
Hello, please contact our support from the licensed account regarding this issue.
