### ISSUE TITLE
Eventcalendar crashes when resources from Immer.js reducer

### ISSUE THREAD

**Issue by jorgenader** [acidb/mobiscroll#520]
Issue occurs when rendering calendar with resouces from Immer based reducer.

Example reducer:
```
import {produce} from 'immer';
const reducer = produce((state, action) => {
    switch (action.type) {
        case 'resources':
            state.resources = action.payload;
            break;
    }
});
```

and in the component rendering the calendar:

```
const [state, dispatch] = useReducer(reducer, initialState);
...

<Eventcalendar resources={state.resources} ... />
```

Mobiscroll version: 5.26
Immer: 9.0

**Comment by dioslaska** [comment]
Currently the eventcalendar does not work with immutable objects (resources, events).
We're planning to make it work, until than the workaround is to pass a deep copy of the data, which is not immutable.

**Comment by dioslaska** [comment]
We added the [immutableData](https://docs.mobiscroll.com/react/eventcalendar#opt-immutableData) option in 5.28.0, when set to `true`, the calendar will not modify the passed data.
