### ISSUE TITLE
Scheduler calendar label issue

### ISSUE THREAD

**Issue by hammadch4sure** [acidb/mobiscroll#521]
![image](https://github.com/acidb/mobiscroll/assets/132783963/4608dc29-8759-4daa-8009-ba6446def650)

Scheduler calendar is updating the wrong month label.
Please try to fix ASAP

**Comment by dioslaska** [comment]
This is because in the loaded week view there are dates from both February and March.
Also, in 5.28.0 we improved the navigation picker, so a day can be also selected, not just month.
