### ISSUE TITLE
Webpack Module Federation - no version specified

### ISSUE THREAD

**Issue by w-komor** [acidb/mobiscroll#526]
Hi!

In my setup, `@mobiscroll\angular-ivy@5.29.1` is a shared singleton in Webpack Module Federation.

I'm getting the following console warning:

`No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file <my-project>\node_modules\@mobiscroll\angular-ivy\dist\esm5\package.json, or manually specify version in shared config.
`

The issue is that Webpack doesn't go upstream to `@mobiscroll/angular-ivy/package.json` to get the MobiScroll version.

The solution is to add the version number to `dist/esm5/package.json` at build time.

[This issue in Webpack](https://github.com/webpack/webpack/issues/13457) may be relevant.

---

For anyone needing a temporary workaround to get rid of the console warning in your production app,  add `requiredVersion: '*'` to your Module Federation options for `@mobiscroll/angular-ivy`

**Comment by Demozsok** [comment]
Hi @w-komor,

Good news: we have shipped [Mobiscroll 5.31](https://mobiscroll.com/releases#product-v5310), where we added the version field to the package.json file of the esm5 folder inside the npm packages, required by some bundlers, e.g. webpack with federated modules.
 
Here you can find a guide on how you can update the Mobiscroll version to the latest: https://mobiscroll.com/docs/angular/guides/update-version.

Let me know if there is anything else.
