### ISSUE TITLE
Feature request: use "em" or "rem" instead of "px" on mobile

### ISSUE THREAD

**Issue by arleytriana** [acidb/mobiscroll#98]

**Comment by dioslaska** [comment]
Currently the following themes are using em values:

  - Mobiscroll (light/dark)
  - Material (light/dark)
  - Android Holo (light/dark)
  - Windows Phone (light/dark)
  - iOS

That means, that changing the font size on the `.dwwr` element will scale the popup size, e.g.:

    .mbsc-mobiscroll .dwwr { font-size: 20px; }

Wheel item width and heights are still in pixels and passed as initialization setting in JavaScript.

The following themes will not be updated and will be probably removed in the future

  - iOS classic
  - Android (old)
  - Sense UI
  - Sense

The jQuery Mobile and Bootstrap themes are mostly using the classes and styles of the respective framework.
